### ISSUE TITLE
Handling input to G_FTEXT objects through FORM_DO() will always filter out SPACEs 

### ISSUE THREAD

**Issue by GokMasE** [freemint/freemint#337] opened 2024-05-14 21:23 UTC
Entering text in a G_FTEXT object via FORM_DO() will always filter out SPACEs even if the te_pvalid parameter is set to allow them. Interestingly, using ALT+032 to sneak a SPACE in there will still work.

I am attaching a tiny test binary demonstrating the issue, with te_pvalid set to "a", which should allow both upper/lower case letters and also SPACE. [frmdobug.zip](https://github.com/freemint/freemint/files/15313756/frmdobug.zip) 

(Chances are that FORM_DO might be using FORM_KEYBD internally, and thus the error might actually reside in there)

**This bug is NOT present in xaaes-ozk (#241 )**

**Comment by th-otto** [comment] 2024-05-15 08:42
I cannot reproduce that:

![Screenshot_20240515_103851](https://github.com/freemint/freemint/assets/12425871/abf6f072-0e61-43bb-9efb-b6ece5c06935)

Text was entered just normally without any tricks. Also i think that it is strange that using ALT+032 behaves differently, since all it does it inserting a space in the keyboard buffer (however without scancode IIRC).

Do you maybe have some other program running that does some keyboard mapping?

**Comment by GokMasE** [comment] 2024-05-15 10:00
To my knowledge I don't have any utility for keyboard mapping/remapping enabled. I will double check that tonight.
Problem was the same on Falcon as well as V4SA, the latter using XaAES binary from february 2024.

**Comment by GokMasE** [comment] 2024-05-15 11:29
Out of curiosity - did you test this from aranym or with native hardware?

I can see this problem only with xaaes-cur, it does not happen with xaaes-ozk, n.aes or myaes.

Another thought: Would there be any setting in XAAES.CNF that could theoretically affect this?

**Comment by th-otto** [comment] 2024-05-15 11:39
From aranym.

I don't think that xaaes.cnf can have any influence, but the keyboard.tbl loaded by mint maybe. I'm using a german keyboard  & definition file.

**Comment by GokMasE** [comment] 2024-05-15 20:49
Well, after MUCH trial and error I can conclude that the trigger for this behaviour IS originating from a keyword within XAAES.CNF.
Try adding this to the config file:

**app_options = default, spaceXinsert=true**

The history for this IIRC was that Helmut quite early on during his XaAES endavour started editing/changing some elements in the keyboard navigation that Ozk had crafted during his time as maintainer. One thing that was now changed was that the concept was tweaked to include list boxes (IIRC) and when that happened, Helmut seems to have decided that SPACE should be used to control those. Since SPACE was already very much in full use with the generic keyboard navigation (used to select the object currently marked as active, indicated with a red dotted rectangle) , the INSERT key was now linked to this functionality instead.

So, this meant that already established key shortcuts was now rather abruptly changed with the SPACE key now linked to another (in GEM context probably much less frequntly used) functionality.

The keyword spaceXinsert for app_options was introduced as a way to allow ppl to get the previously normal behaviour back - and when I learned about it I added it to xaaes.cnf immediately and thought nothing more of it.

Now it seems like this "fix" introduced further issues.
As it stands, having this keyword active certainly prevents normal input to edit fields, so my hopes are that this can be solved in a clean way.

**Comment by lpgb** [comment] 2024-05-15 21:05
Tried the above config option on my xaaes test setup and sure enough it breaks form_do(). Spacebar stops working in forms where it's suppose to allow spaces. Oddly alt-032 manages to inject a space into a form as @GokMasE noted, but that's a kludgy workaround.

**Comment by th-otto** [comment] 2024-05-16 04:09
The reason why alt-032 works is simple: ascii codes entered this way don't have a scancode, but the option uses the value returned from the spacebar:
https://github.com/freemint/freemint/blob/1c847511503b8caa1b727409adab56c2577046ab/xaaes/src.km/cnf_xaaes.c#L665-L671
https://github.com/freemint/freemint/blob/1c847511503b8caa1b727409adab56c2577046ab/xaaes/src.km/keycodes.h#L32

And the reason why that option breaks editable fields is also simple: that mapping is always done without checking for the type of the current object. I could imagine that using INSERT would insert a space in those case.

**Comment by GokMasE** [comment] 2024-05-16 04:45
Exactly what you say, SPACE is well established as a way to select button in dialogs so the use of INSERT instead was (and is) questionable. One could argue that the need for this workaround in the first place is a result of bad design choices.

The question now is whether it would make more sense to restore the original key mappings for keyboard navigation or if the "spaceXinsert" option should better be fixed.

**Comment by th-otto** [comment] 2024-05-16 04:52
Ah ok, now i get it. I was wrong with that, current behaviour (without the option) is to select buttons with INSERT.

There are also other strange inconsistencies. Eg. in https://github.com/freemint/freemint/blob/1c847511503b8caa1b727409adab56c2577046ab/xaaes/src.km/xa_fsel.c#L2536 key_conv() is called, but in scrl_cursor() it is called again, swapping the key twice.

I would vote for removing that option altogether, and restore the previous behaviour.

**Comment by GokMasE** [comment] 2024-05-16 11:27
Unless someone feels very strongly for the current default setting, I think that would be a suitable way to handle it.
It sounds like current implementation of spaceXinsert is adding somewhat of a kludge.

**Comment by th-otto** [comment] 2024-05-16 12:45
For the record: changes were introduced with https://github.com/freemint/freemint/commit/63da70ba59baaa1389b707b32c1580b736dcaa18, with original changes coming from https://github.com/freemint/freemint/commit/57527f7dc0c5c318466cb680de9b70b2afdc98bf

Both are troublesome: the first one is a large, merged commit will all changes from helmuts branch, while the 2nd is incomplete (there were further fixes later).

**Comment by th-otto** [comment] 2024-05-16 13:11
BTW, when you speak about xaaes-ozk, do you mean XaAES build from the https://github.com/freemint/freemint/tree/obsolete/ozk-enhancements branch, or are there any other mysteries involved?

**Comment by GokMasE** [comment] 2024-05-16 14:03
IIRC, ozk-enhancements is the origin but afaik @mikrosk adapted that version of XaAES to the newer kernel API back in 2022.
Shortly after this, a couple of bugfixes were also backported to it.  AFAIK it does not have a branch of its own at this time, but this version is what is referenced in #241 which also should have a link to binary. Any further questions for details would have to be directed to mikro ;-)

**Comment by th-otto** [comment] 2024-05-16 15:25
Just pushed a fix for this. Could you please test it? It now uses the old (2009) behaviour again of using SPACE to select buttons. Until now i didn't know that INSERT was used for it.

The opposite setting was used in lists (ie.  in the fileselector). Hopefully did not break anything important there, i'm not even sure how space/insert was supposed to work there.

**Comment by mikrosk** [comment] 2024-05-16 18:19
Thanks, Thorsten. Like you, I also hadn't noticed this weirdness. It shouldn't have made it into code in the first place.

xaaes-ozk is a working title for builds published in #241 and available in https://github.com/mikrosk/freemint/tree/before_helmut. Mainly due to my laziness but also due to lack of some final decision it is still in my tree only.

As I'm probably the least demanding user of (Xa)AES ever, I like the idea of 'clean' XaAES without all the questionable Helmut choices/features. I don't deny that a decade worth of commits had brought also some nice fixes/features so I don't have an answer what and how to do it, especially considering the nature of Helmuts commits (big and changing many features at once).

@GokMasE, is the "broken keyboard navigation" in #241 still valid? Oh and btw, if you want to spare yourself some time, always just grab https://tho-otto.de/snapshots/freemint/bootable/freemint-latest-02060-tt_falcon_clones.zip, boot it, test the behaviour and report afterwards. Not a single thing on your present config will be changed, you can safely delete the whole c:\mint\1-19-<id> folder afterwards.

**Comment by GokMasE** [comment] 2024-05-16 19:52
Thanks for pushing a fix for this @th-otto 

I can confirm that the spaceXinsert setting is no longer needed to get back the "old" default behaviour for SPACE key (ie, selecting buttons in dialogs). Typing text to input fields is now working like expected, even when SPACE is involved.

ATM I can't seem to notice anything broken with regards to the file selector either - it seems to behave like it did before todays change.

@mikrosk, regarding "broken keyboard navigation" - I will try to get back to you on this soon, it has been a while since checking into details.

**Comment by GokMasE** [comment] 2024-05-17 11:46
Since the problem with FORM_DO/FORM_KEYBD seems resolved as of the pushed fix, maybe this issue should be marked as resolved?

(The remaining issue with keyboard nav, as described in previous post, is perhaps better destined for a separate bug report)

**Comment by mikrosk** [comment] 2024-05-17 12:43
Ok, I have updated #241's "broken keyboard navigation" and we can close this one.

**Closed by mikrosk** 2024-05-17 12:43 UTC
