### ISSUE TITLE
asix.xif shipped in "000" build is in fact built for 68020

### ISSUE THREAD

**Issue by czietz** [freemint/freemint#84] opened 2018-04-01 19:31 UTC
Today I was asked by a Lightning VME user to investigate why FreeMiNT hangs on a MegaSTE when loading the driver for the Ethernet chip asix.xif. As it turns out, the version shipped in the "000" build (as megaste/asix.xix) is in fact **not built for a 68000 CPU**.

Consider for example the code for init():
```
000000E4 loc_E4:
000000E4                 move.l  4(sp),(dword_11E8).l
000000EC                 move.l  8(sp),(dword_11E4).l
000000F4                 jsr     (sub_F4C).l           ; driver_init()
000000FA                 tst.l   d0
000000FC                 sne     d0
000000FE                 extb.l  d0
00000100                 neg.l   d0
00000102                 rts
```

`extb.l` is a 68020-and-above instruction.

There must be something wrong with the build system. Probably object files are not rebuilt for each CPU. Please fix the Makefile accordingly.

PS: Other xif drivers might be affected as well. I didn't test.

**Comment by czietz** [comment] 2018-04-01 19:40
We have the offending line right here: main.o is only built once and it is build for 68020-60:
https://travis-ci.org/freemint/freemint/jobs/356849735#L1264

All drivers that link this main.o will have the issue on a 68000. Seems like no one uses MintNet on a 68000?

**Comment by th-otto** [comment] 2018-04-01 20:03
Seems that rtl8012 is the only driver which is explicitly compiled for 020. A patch like 

`
--- Makefile.orig       2018-04-01 21:54:03.225301364 +0200
+++ Makefile    2018-04-01 21:55:07.205299972 +0200
@@ -174,8 +174,9 @@
 rtl8012:
        $(MAKE) rtl8012.xif \
                "TARGET=rtl8012.xif" \
-               "XOBJS=$(COMMON_OBJS) $(RTL8012_OBJS)" \
+               "XOBJS=main_020.o $(RTL8012_OBJS)" \
                CPU=020-60
+main_020.o: main_020.c
 
 rtl8012st:
        $(MAKE) rtl8012st.xif \
@@ -185,5 +186,8 @@
 rtl8012st.c:
        ln -s rtl8012.c $@
 
+main_020.c: main.c
+       ln -s $< $@
+
 
 include $(top_srcdir)/DEPENDENCIES
`

Should do the trick. OTOH, if nobody complained before, maybe the infra-structure there should be changed to compile *all* drivers by default for 020 instead? Or use sub-directories like in other dirs, to compile all drivers for all cpu types.

**Comment by czietz** [comment] 2018-04-01 20:16
What would be the actual benefit of compiling all drivers for 020? Excluding 68000 users from MiNTNet?

PPS: Use **three** backticks (e.g. ```) to mark multi-line blocks of code.

**Comment by th-otto** [comment] 2018-04-01 20:25
@czietz no I don't want to exclude them, but apparently currently all drivers use the main module compiled for 020, and nobody noticed before. As already said, the cleanest solution would be to use subdirectories for each cpu type. A simple solution might be to just don't compile the rtl8012 driver for 020 (dunno wether that makes much difference in speed).

**Comment by DavidGZ** [comment] 2018-04-02 07:31
Wow.....perfect timing, I'm working right now on the ST version of the RTL8012 driver and I'm hitting this problem too. The driver hangs after the "driver_init()" function. Still I find some strange things. If the problem is an illegal instruction why the system didn't give an "Illegal Instruction Exception"?. And what is strangest, I don't have the RTL8012 hardware but I've by-passed the driver probe function and I'm able to replicate the hang in a CT60 Falcon with the 020-60 version of the driver but not with the 060 version. Also the hang problem is not there some commits ago, I suspect this commit introduce the issue (859360bb9707e17ffff3aa9684c0947f3f1b4f71), but I still have to confirm it.

About the main.c being compiled for the 020-60 the workaround is easy, the RTL8012 driver shouldn't be in the first place in the Makefile's DRIVERS list. I'll fix this.

**Comment by th-otto** [comment] 2018-04-02 07:39
Only moving it around will not fix this. In either case you will end up with a main.o that is compiled for a specific architecture, while in fact you need it for at least 2 different architectures (if you want to keep the 020 version for rtl8012). With a single main.c, you will never know how it was compiled, especially when doing parallel makes.

**Comment by czietz** [comment] 2018-04-02 07:49
@DavidGZ : All I can say is that doing a `make clean && make CPU=000 CROSS=yes asix` (thereby also compiling main.c for the 68000) resulted in a working asix.xif. Since this solved the problem for the user and me, I didn't investigate further, e.g. why there is no exception shown. I assumed this was maybe switched off while processing modules. (That's loading a module, asix.xif, from within another module inet4.xdd.)

**Comment by DavidGZ** [comment] 2018-04-02 08:11
@th-otto : OK, I understand. What about deleting main.o after every driver built? I did a quick test and it looks that it does the trick.

**Comment by DavidGZ** [comment] 2018-04-02 08:17
@czietz : I guess compiling main.c for the 68000 also will solve my problem, but I'm going to investigate further just in case there is something else hiding.
Thanks for reporting about this, it saved me some hours of "hunting" the bug.

**Comment by th-otto** [comment] 2018-04-02 08:20
@DavidGZ that will also barf with parallel makes. Either it is just rebuild by some other job, or that job aborts when linking because it was removed by some other make. The small patch i posted should do it for our current scenario (only main.o needs to be compiled for 020). It follows the same approach as compiling the rtl8102 source also as rtl8102st. Alternatively, you could just create a main_020.c that includes main.c.

**Comment by DavidGZ** [comment] 2018-04-02 09:00
@th-otto : Sorry I was missing that you've proposed a patch above while I was suggesting solutions. I'll test and submit your patch.

**Comment by DavidGZ** [comment] 2018-04-02 17:37
The patch has been pushed.
In addition to the patch above I've added main_020.c to .gitignore and I've made the rtl8012 driver for the 060 link with main_020.o too.

**Closed** 2018-04-04 07:12 UTC
