### ISSUE TITLE
Deadkeys disabled on FireTOS?

### ISSUE THREAD

**Issue by RajahLone** [freemint/freemint#164] opened 2020-04-15 16:01 UTC
From latest versions, the deadkeys don't work evenif they are configured in the *.tbl file.

**Comment by DavidGZ** [comment] 2020-05-03 12:01
I've just tested kernel's deadkeys functionality, and it's working fine here on aranym with a kernel compiled from today sources.
Could it  be that your keyboard.tbl got corrupted? or may be the correct keyboard.tbl file is not in the system directory for the kernel you have been using?

**Comment by RajahLone** [comment] 2020-05-03 12:09
Firebee setupn French *.tbl for MegaST French keyboard. I'm not using Aranym.

I tried/retried a large amout of times to rebuilt the tbl file from the setup app or take it from archives that worked. No effect. The tbl works fine, French characters are displayed accordingly to the keyboard keys.

**Comment by vinriviere** [comment] 2020-05-03 12:28
I always wondered if the keyboard interface between FireTOS and FreeMiNT was really robust.

**Comment by DavidGZ** [comment] 2020-05-03 14:01
> Firebee setup French *.tbl for MegaST French keyboard. I'm not using Aranym.
> 
> I tried/retried a large amout of times to rebuilt the tbl file from the setup app or take it from archives that worked. No effect. The tbl works fine, French characters are displayed accordingly to the keyboard keys.

I understand your report as it was working before and after a kernel upgrade it's not working anymore, is it so? If it's true do you remember around which date was compiled the last working kernel?

**Comment by RajahLone** [comment] 2020-05-03 14:22
1/1.5 year at least, maybe 2 years ago. 

Can't remember the versions, sorry. Having a git-hash for releases numbers doesn't help low-end users.

**Comment by DavidGZ** [comment] 2020-05-03 17:56
I've found the culprit: commit 625241ae26f8a726eccb557a824d61159067faed
This was done because some FireBee and CTPCI users were annoyed by a pop-up message from FireTOS complaining about an incompatibility in MiNT's kernel keyboard handling. I think USB keyboard users were affected.

It's not that deadkeys don't work, it's that the keyboard.tbl file is not used at all.
Kernel running over EmuTOS on the FireBee works fine regarding deadkeys, only FireTOS is affected.

I'll take a look at the code to see if there is something we can do from the kernel.

**Comment by DavidGZ** [comment] 2020-05-04 08:25
Some more background to the original issue:

https://sourceforge.net/p/freemint/mailman/message/36802747/

**Comment by DavidGZ** [comment] 2020-05-05 10:11
I don't know for sure because I have no access to FireTOS sources, but I think the problem is that FireTOS ikbdsys handler doesn't call the undocumented KBDVEC vector handler as other TOS>2.00 versions do. If this is the case a possible solution would be to treat FireTOS as a TOS<2.00, still we need to confirm what happens with USB keyboards, I don't have one for testing this.

As a side effect while investigating this I found 2 other issues introduced by the commit mentioned above which affects MiNT running over TOS versions < 2.00 , I'll fix them too.

**Comment by vinriviere** [comment] 2020-05-05 10:49
I remember that Didier complained, because as FreeMiNT hooks the ACIA handler, he wasn't able to properly generate Keyboard/Mouse events as he did successfully for TOS/EmuTOS. I never investigated that myself.

Note that the kbdvec vector introduced in TOS 2 is hardware-independant, but handles only keyboard events. While ikbdsys handles all bytes from IKBD protocol (keyboard, mouse, joystick...) but has the big drawback of being hardware-dependent (it reads data from the ACIA).

For information, EmuTOS introduce a private function named ikbdraw. This one handles all IKBD bytes, and is hardware-independant. It is used for example to allow plugging an Atari keyboard on an Eiffel adapter, then connect it to a ColdFire Evaluation Board on the CAN port. The low-level EmuTOS driver receives bytes from the CAN bus (IKBD protocok) then forwards the bytes to the internal ikbdraw for standard processing. Of course, on Atari hardware, ikbdsys also calls ikbdraw internally, just after having fetched the bytes from the ACIA. It may be worth make EmuTOS ikbdraw public some day, with a well-defined interface, so third party drivers could easily produce Keyboard / Mouse / Joystick events for maximum compatibility. Such interface could even be added to Atari TOS through a TSR.

**Comment by DavidGZ** [comment] 2020-05-05 11:29
> I remember that Didier complained, because as FreeMiNT hooks the ACIA handler, he wasn't able to properly generate Keyboard/Mouse events as he did successfully for TOS/EmuTOS. I never investigated that myself.
> 

I saw a comment from you in the sources wondering why it was needed to hook the ACIA interrupt, I don't have an answer either. Now this only affects when MiNT runs over TOS<2.00 but at some point ozk forced it for all hardware but the Milan. Besides when MiNT's ACIA interrupt handler calls VMIDISYS vector the system crashes, ozk commented that call. I didn't investigate yet why of that crash but I'm going to test removing MiNT's ACIA interrupt, if it works I would remove it definitely.

**Comment by DavidGZ** [comment] 2020-05-05 11:50
Removing MiNT's ACIA handler makes the system crash as soon as you move the mouse, so I guess MiNT's ikbdsys handler depends of that ACIA handler somehow.

**Comment by vinriviere** [comment] 2020-05-05 12:00
That looks really abnormal. That code must be investigated. It has been messed for too much time (including MIDI). Note: when such crash on interrupts occurs, as usual key points to check are correctness of saved/restored registers, and supervisor stack size. But as the issue appears when removing the handler, this must be something else.

**Comment by DavidGZ** [comment] 2020-05-06 08:29
> That looks really abnormal. That code must be investigated. It has been messed for too much time (including MIDI). Note: when such crash on interrupts occurs, as usual key points to check are correctness of saved/restored registers, and supervisor stack size. But as the issue appears when removing the handler, this must be something else.

At the end was something trivial, the addres to reference the KBDVECS table is placed in an address register in MiNT's ACIA interrupt handler, when MiNT's ikbdsys handler is called from TOS ACIA handler that address register has a bogus value. Copying the correct value again in the ikbdsys vector routine solved the crash.

**Comment by DavidGZ** [comment] 2020-05-06 08:45
> I saw a comment from you in the sources wondering why it was needed to hook the ACIA interrupt, I don't have an answer either. Now this only affects when MiNT runs over TOS<2.00 but at some point ozk forced it for all hardware but the Milan. Besides when MiNT's ACIA interrupt handler calls VMIDISYS vector the system crashes, ozk commented that call. I didn't investigate yet why of that crash but I'm going to test removing MiNT's ACIA interrupt, if it works I would remove it definitely.

This problem is like the other one but the opposite, TOS ACIA vector handler puts in a address register an address to reference its internal variables, TOS midisys routine expect that address register to have the correct value so it doesn't set it by itself, when MiNT's hooks its own ACIA handler the address register needed by TOS midisys handler has a bogus value.
Note that MiNT doesn't implements a midisys handler and use the one from ROM. So I think this the final push to avoid to use MiNT's own ACIA handler. I've tested it and now it works OK.
Yesterday I was thinking that a possible reason to why an ACIA handler was implemented is becuase some previous kernel developers had the idea to get MiNT's TOS dependency to the minimum, and this was a step more in that direction. Just a theory. I won't remove the ACIA handler code I'll place a comment and I'll only delete where the handler is hooked.

**Comment by vinriviere** [comment] 2020-05-06 09:15
Excellent investigation, @DavidGZ 😀
Let's get rid of that FreeMiNT ACIA hook, as you propose. It isn't required when FreeMiNT runs on TOS >2 or EmuTOS.
But what will happen when FreeMiNT runs on TOS 1 ? We must handle that situation. Use the ACIA hook only in that case ?

**Comment by th-otto** [comment] 2020-05-06 09:33
I rather would propose the opposite instead, and implement a midisys handler (at least some default that does not crash).

Generally, i agree that the idea was probably to be independent of the underlying OS, and that should really be how it is done.

**Comment by skaftetryne** [comment] 2020-05-06 09:41
On 06.05.2020 10:46, DavidGZ wrote:

> Yesterday I was thinking that a possible reason to why an ACIA handler 
> was implemented is becuase some previous kernel developers had the idea 
> to get MiNT's TOS dependency to the minimum, and this was a step more in 
> that direction. Just a theory. I won't remove the ACIA handler code I'll 

This is correct. One of Frank Naumann's goals was to get rid of as much 
TOS dependencies as possible.

Jo Even

**Comment by DavidGZ** [comment] 2020-05-06 09:54
> Excellent investigation, @DavidGZ grinning
> Let's get rid of that FreeMiNT ACIA hook, as you propose. It isn't required when FreeMiNT runs on TOS >2 or EmuTOS.
> But what will happen when FreeMiNT runs on TOS 1 ? We must handle that situation. Use the ACIA hook only in that case ?

When we run on TOS 1 MiNT's own ikbdsys vector handler is installed, and this handler unlike TOS <2.00 ikbdsys handler will called the undocumented kbdvec. ACIA hook isn't needed any more. I've tested with Hatari running on TOS 1.62, it works fine, external key tables and dead keys.

**Comment by DavidGZ** [comment] 2020-05-06 10:06
> I rather would propose the opposite instead, and implement a midisys handler (at least some default that does not crash).
> 
> Generally, i agree that the idea was probably to be independent of the underlying OS, and that should really be how it is done.
> 

I'm not against doing this but until someone completes the implementation of everything need it at least the system doesn't crash.

> BTW, not calling the custom ACIA handler at all would prevent use of any keyboard table file.

ACIA handler isn't necessary it, what it's needed is a ikbdys vector handler which calls the undocumented kbdvec vector. Only TOS 1 ikbdsys handler doesn't do that (well TOS 1 and it seems that FireTOS too) in this case we hook our own ikbdsys routine, then external keyboards table files work also.

**Comment by th-otto** [comment] 2020-05-06 10:09
If that is easier for now, then go ahead. But please don't close this issue (or open a new one). I don't like the idea of providing drivers for all hardware, except for keyboard/mouse.

**Comment by DavidGZ** [comment] 2020-05-06 10:15
> If that is easier for now, then go ahead. But please don't close this issue (or open a new one). I don't like the idea of providing drivers for all hardware, except for keyboard/mouse.

I'm not ready yet I still need to handle the FireTOs case, when that is solved I will close this issue and open a new one regarding completing the keyboard/mouse drivers.

**Comment by DavidGZ** [comment] 2020-05-06 11:10
https://github.com/freemint/freemint/commit/c3c065c2e32c1a74c62b0e552885c3a876a1f9b2

**Comment by vinz6751** [comment] 2020-05-06 11:13
Hi !


Doing a bit of MIDI, I think TOS's MIDI support is quite limited, for 
example, TOS doesn't support basic things like:

  * Reading more than one byte (Midiws can write, but there is no such
    things as Midirs)
  * Sending data under interrupt
  * Timestamping (bytes gets into the IOREC buffer but you don't know
    when they were received).

All this (and more) could be done much better with a XDD providing a 
MIDI device driver (I wrote one for 1.15.12 but it's probably broken 
now). If FreeMiNT is not bringing any benefit in MIDI handling, then I 
don't see the point of duplicating what the TOS already does, and 
falling back on sounds just fine to me.


Vincent B


Le 06/05/2020 à 12:15, DavidGZ a écrit :

**Comment by vinriviere** [comment] 2020-05-06 11:20
As far as I understand from the above information (and old memories), there are 2 hooks in FreeMiNT:
- One to hook the ACIA vector, only useful on TOS 1 as it lacks the kbdvec vector
- Second one to hook the kbdvec vector in order to implement advanced scancode to ASCII translation.

So I completely agree with @DavidGZ . The ACIA hook has only to be used when necessary, concretely on TOS 1 because it lacks the indispensable kbdvec vector. This is a FreeMiNT workaround which must be seen as "BIOS update".

> If that is easier for now, then go ahead. But please don't close this issue (or open a new one). I don't like the idea of providing drivers for all hardware, except for keyboard/mouse.

Please close this issue when the original question (deadkeys on FireTOS) is resolved. Other conceptual questions should go into a new dedicated issue (if something has to be fixed) or the mailing list.

Regarding to FreeMiNT "providing drivers for all hardware", this is completely wrong. On the contrary, FreeMiNT relies on the underlying BIOS for hardware access. So concretely, FreeMiNT is almost hardware-independent. I could verify that when porting FreeMiNT to ColdFire emulation boards or Amiga: FreeMiNT requires almost zero patch for specific hardware (not strictly 0, but this could be discussed elsewhere). It just relies on the underlying BIOS, and EmuTOS provides it for non-Atari hardware. Then FreeMiNT replaces the GEMDOS layer, no trouble with that.

**Comment by skaftetryne** [comment] 2020-05-06 18:17
> Regarding to FreeMiNT "providing drivers for all hardware", this is completely wrong. On the contrary, FreeMiNT relies on the underlying BIOS for hardware access.

Correct, the kernel does not provide drivers for much hardware. But it was Frank's goal to make FreeMiNT as TOS-independent as possible. E.g. he added the ACIA handler, serial drivers and FAT fs in order to allow MiNT to not depend on buggy TOS and TOS patches. He also intended to write a floppy driver and add background DMA transfers for floppy, ACSI and SCSI.

Now, with the huge improvements in EmuTOS the last few years this may not be as important anymore.  OTOH, one way to go could be to remove as much hardware dependancy as possible in MiNT and instead create a pure (X)BIOS replacement for MiNT from EmuTOS sources.

**Comment by DavidGZ** [comment] 2020-05-07 10:29
At the end FireTOS doesn't behave like TOS <2.00, it doesn't even called the ikbdsys vector from its ACIA interrupt handler, perhaps it calls its internal ikbdsys routine directly without checking the vector in the KBDCEVS vector table. If I can confirm this I'm afraid that the only solution is to hook again MiNT's ACIA handler, for FireTOS at least.

**Comment by vinriviere** [comment] 2020-05-07 12:20
IIRC, FireTOS used to call Kbdvbase() at startup, then hook the kbdvec vector. But Didier told me he had trouble with FreeMiNT. And that would make sense, because if FireTOS only reads the vectors addresses at startup, and FreeMiNT replaces the vectors with its own ones, then FireTOS will always hook the wrong vector (TOS one, not FreeMiNT one). Then some day Didier told that he found a solution for FreeMiNT, I don't know which. I may remember that it had not always worked well with all subsequent FreeMiNT versions. I just hope that Didier hadn't used some hardcoded vector address. BTW, FreeMiNT has some flags to detect actual TOS kind. If it is the last thing to do, we could keep the ACIA hook for FireTOS only, and remove it for other clean OSes.

**Comment by th-otto** [comment] 2020-05-07 13:01
On Donnerstag, 7. Mai 2020 14:20:51 CEST Vincent Rivière wrote:
> And that would make sense, because if FireTOS only reads the vectors
> addresses at startup, and FreeMiNT replaces the vectors with its own ones,
> then FireTOS will always hook the wrong vector

But isn't that a bug in FireTOS then? Those vectors are all well documented, 
and could be hooked by *any* program, not only freemint.

**Comment by DavidGZ** [comment] 2020-05-07 15:45
After disassembling it seems that FireTOS hooks the ikbdsys vector handler directly into the ACIA interrupt vector. 
The ACIA handler from other TOS I've seem jump into midisys and ikbdsys as soon as possible, as you can see below FireTOS doesn't jump to any relative address and it looks totally like ikbdsys handler.

[firetos_acia.txt](https://github.com/freemint/freemint/files/4594010/firetos_acia.txt)
(I tried to paste the code in the message but the formatting gets all messed up)

This explains why the efforts to make MIDI work on FireTOS last October in the FireBee forum didn't crystallize, they patched FireTOS and fixed MIDI out and MIDI through but they gave up with MIDI in, besides they reported that MIDI in messages freeze ATARI keyboards.

**Comment by vinriviere** [comment] 2020-05-07 15:46
There are 3 levels of hooks:
- ACIA, vector at 0x118, for both IKBD and MIDI). Handler _was_ _new_acia.
- ikbdsys, for IKBD ACIA only. Handler is _ikbdsys_handler.
- kbdvec, for IKBD keyboard data only (hardware-independant). Handler is _newkeys.
They must not be confused. See https://github.com/freemint/freemint/blob/master/sys/arch/init_intr.c#L89 for details.

That being said: I thought that FreeMiNT replaced the whole vector **table** (I mean the value returned by Kbdvbase(). But unless I've just missed something, I was wrong. It seems that FreeMiNT only hooks vectors inside the TOS vectors table. I was fooled by the expression "oldkey = *syskey" which just backups the whole table for eventual restoration later.

But loot at the code just after: kbdvec (the "undocumented" vector at offset -1) is hooked in all cases, including in TOS 1 !! As far as I know, there is no proof that there is some free memory on TOS 1 at that place. If so, that should be explicitly documented in FreeMiNT sources. But that's likely to be a bug on TOS 1.

This code was a mess. I changed it for non-Atari hardware, I don't think it is worse than before. On the contrary it is more readable now. So problems can be seen more easily. If I'm not mistaken, from what I said above, there is a serious keyboard issue with FreeMiNT on TOS 1. This must absolutely be investigated and fixed.

**Comment by vinriviere** [comment] 2020-05-07 15:51
Excellent investigation, @DavidGZ !

NB : To insert code here, paste, then select all the lines. Then click <> above. That will add ``` at the beginning and the end. Then code will be displayed correctly.
```
   87994:      4e56 fffc            linkw %fp,#-4          <- start of the ACIA handler
   87998:      4fef ffc8            lea %sp@(-56),%sp
```

**Comment by DavidGZ** [comment] 2020-05-07 15:52
>BTW, FreeMiNT has some flags to detect actual TOS kind. If it is the last thing to do, we could keep the ACIA hook for FireTOS only (as you suggest), and remove it for other clean OSes.

Good, I've been thinking about this, I know the "tosver" flag but I didn't find other that gives information about if FireTOS is running, I was thinking about creating one. Besides CT60 TOS 2.0x must be affected too by this issue, and I don't know yet how can I get on which CT60 TOS version is the kernel running on.

**Comment by DavidGZ** [comment] 2020-05-07 16:16
> But loot at the code just after: kbdvec (the "undocumented" vector at offset -1) is hooked in all cases, including in TOS 1 !! As far as I know, there is no proof that there is some free memory on TOS 1 at that place. If so, that should be explicitly documented in FreeMiNT sources. But that's likely to be a bug on TOS 1.
> 

You're right we don't know what there is in that address in TOS 1. I'm going to check it but to be completely safe I'm going to copy the KBDVBASE table to a new location. MiNT handles already Kbdvbase() XBIOS system call.

**Comment by DavidGZ** [comment] 2020-05-07 16:26
OK, thanks a lot for the info, I forgot about the coldfire_68k_emulation flag.

>  Regarding to the CT60 TOS, if it really has the same issue, then you will have to detect FireTOS differently.

The problem with CT60 TOS is that only version 2 would be affected, the one which supports the CTPCI hardware, version 1 which is the version that most people use, is OK and it doesn't have this issue.

**Comment by vinriviere** [comment] 2020-05-07 16:59
> You're right we don't know what there is in that address in TOS 1. I'm going to check it but to be completely safe I'm going to copy the KBDVBASE table to a new location. MiNT handles already Kbdvbase() XBIOS system call.

Ah, you're right. FreeMiNT hooks the XBIOS in this case, I missed it. FreeMiNT's implementation of Kbdvbase() is sys_b_kbdvbase() in sys/keyboard.c. But that looks completely dumb, because it returns the syskey value, which has been retrieved from the ROM !! I suspect that code to have been reworked several times in the past. But currently, this Kbdvbase() looks useless. And indeed, the safe way would be to hook Kbdvbase() only for TOS 1, in order to use a new vector table to ensure there is enough room to add the kbdvec vector. But beware! If FireTOS caches the Kbdvbase() return value on startup (as it did previously), replacing the full table afterwards will defeat it. Same with eventual TSR in the AUTO folder.

Another option would be that FreeMiNT never tries to replace the vector table (as currently), and not even hook Kbdvbase(). Then FreeMiNT should only use kbdvec on TOS > 1. And instead, hook ikbdsys only on TOS 1, as there is no other way to get keystrokes, and carefully avoid the kbdvec vector in that case. And call the internal kbdvec handler (named newkeys) directly from ikbdsys, without going through the inexistent kbdvec vector. Last case, workaround for FireTOS (hook the ACIA vector??).

Note that Didier added a special workaround in FireTOS only because he considered that FreeMiNT did a wrong thing. And in regard to our discussion, he was probably right. Problem is that, by cleaning FreeMiNT now, FireTOS workarounds may not work anymore. So we need to add workarounds for workarounds, sigh. Really, bugs should be fixed ar the right places instead of add ing workarounds everywhere.

BTW, maybe FreeMiNT hooks Kbdvbase() for reentrency questions. I have no idea.

**Comment by DavidGZ** [comment] 2020-05-07 18:18
> 
> Another option would be that FreeMiNT never tries to replace the vector table (as currently), and not even hook Kbdvbase(). Then FreeMiNT should only use kbdvec on TOS > 1. And instead, hook ikbdsys only on TOS 1, as there is no other way to get keystrokes, and carefully avoid the kbdvec vector in that case. And call the internal kbdvec handler (named newkeys) directly from ikbdsys, without going through the inexistent kbdvec vector. Last case, workaround for FireTOS (hook the ACIA vector??).

This is the idea I like the most, it's already very similar at the state of the code now, we only have to call the handler directly or even better ikbd_scan() from our ikbsys handler which it's already only installed on TOS 1, this is how it was done with the changes of ozk but for all cases but the Milan, and it's the reason for the complains of Didier, because ikbs_scan was not reachable anymore through the kbdvec vector.


> BTW, maybe FreeMiNT hooks Kbdvbase() for reentrency questions. I have no idea.

AFAIK all the calls to the xbios goes through the kernel to improve reentrancy and to be able to control what the user can do depending on his privileges, (see arch/syscall.S). Depending on the call the kernel also do some reimplementation of some functions mainly to fix bugs in ROM implementations but almost all of them end calling the ROM.

**Comment by DavidGZ** [comment] 2020-05-08 06:59
> > Regarding to the CT60 TOS, if it really has the same issue, then you will have to detect FireTOS differently.
> 
> The problem with CT60 TOS is that only version 2 would be affected, the one which supports the CTPCI hardware, version 1 which is the version that most people use, is OK and it doesn't have this issue.

OK, I've found out where Didier's TOS keeps the version number and date, the good thing is that the same values are kept between FireTOS and CT60 TOS, so testing for a version >= 2.00 will be enough for both FireTOS and CT60 TOS.

I'll start a discussion in the list regarding the creation of a new global variable that gives that information.

**Comment by DavidGZ** [comment] 2020-05-09 10:24
741be623c70a806a117d4f8710eec3395f28553c
8172e43783905d77b8fba323b15266412f509a46

With these new commits this issue should be solved.
@RajahLone cold you please test the latest build to confirm it?

**Comment by RajahLone** [comment] 2020-05-09 11:29
@DavidGZ : deadkeys are back and working good with this saturday morning build. Thanks!

**Comment by DavidGZ** [comment] 2020-05-11 14:44
I've been said that USB keyboards are working too. Closing.

**Closed by DavidGZ** 2020-05-11 14:44 UTC
Labels: bug, kernel
