### ISSUE TITLE
Application receives bogus toolbar message at startup

### ISSUE THREAD

**Issue by lpgb** [freemint/freemint#230] opened 2021-09-29 17:59 UTC
When my program starts up it receives a WM_TOOLBAR message even though there isn't any window open with a toolbar. The window I do open has no toolbar and reports handle 14. The message that arrives is as follows:
msg[3]=13 msg[4]=1 msg[5]=0 msg[6]=0
The handle varies depending on how may other apps might be running. It caused my app to freeze and it took me 2 hours to track it down. Solved it by double checking the handle, however should the AES be sending me this message in the first place? It's seems very strange to me.

**Comment by th-otto** [comment] 2021-09-29 18:15
Generally you should always check the handle for window related messages, but of course XaAES should not send such a message if not requested.

I only found 2 places where such a message is send: when you set a toolbar on your window using wind_set(WF_TOOLBAR),  and when you close a window dialog who had a toolbar set. Very strange.

Are you sure you did not call wind_set(), maybe with some wrong constant?

**Comment by lpgb** [comment] 2021-09-30 15:53
I have a wind_set(wind_set(WF_TOOLBAR) just after wind_create() to insure the AES is aware of the toolbar before I call wind_calc(). I've double checked and triple checked it, not much to mess up, if the address or the handle is wrong it either crashes or you don't see a toolbar. ;)

**Comment by th-otto** [comment] 2021-09-30 16:24
Hm. Could that be just a message from some previous wind_set() call that you just did not handle yet because you did not call evnt_multi in between?
I never did toolbars until now (mostly because most AES don't support it anyway), so i cannot tell for sure whether something is wrong in XaAES. Could you maybe provide a small example that demonstrates the wrong behaviour?

**Comment by lpgb** [comment] 2021-09-30 16:43
Yes, I will try and isolate the problem in as test case with sources code.

**Comment by lpgb** [comment] 2021-09-30 19:19
Give this a try. I'm able to trigger the message without opening any windows. Comment out wind_set(WF_TOOLBAR) and the message goes away. Not sure why it's sending a message when attaching a toolbar. That just seems weird.

[tbtest.zip](https://github.com/freemint/freemint/files/7261978/tbtest.zip)

**Comment by jflemaire** [comment] 2021-10-01 06:26
On Thursday, 30 September 2021 21:19:44 CEST Lon Pursell wrote:
> Give this a try. I'm able to trigger the message without opening any
> windows. Comment out wind_set(WF_TOOLBAR) and the message goes away. Not
> sure why it's sending a message when attaching a toolbar. That just seems
> weird.

I haven't looked at my GEM code for a while but I remember receiving 
WM_TOOLBAR messages that I couldn't make heads or tails out of the last time I 
worked on it.

Cheers,
JFL
-- 
Jean-François Lemaire

**Comment by th-otto** [comment] 2021-10-01 11:14
I think there is nothing wrong with XaAES. As noted above, the wind_set(WF_TOOLBAR) will result in a WM_TOOLBAR msg being send. But then you delete the window again. In your mainloop you will then receive  the message for a window that is no longer there.

**Comment by lpgb** [comment] 2021-10-01 14:12
Comment out wind_delete() and move it to the end of the listing. The window is created but not deleted. It still sends the weird message. I have to politely disagree as the documentation states this message arrives when a user physically clicks a toolbar object. If this was a full blown app and I noted the handle, it would pass a simple double check of the handle. One would have to also do another check to test if the window is actually open. In NAES I don't need any double checks, it only arrives on a physical click of a toolbar object.

**Comment by th-otto** [comment] 2021-10-01 16:21
Hm, as noted i have never used toolbars so i cannot tell whether the initial WM_TOOLBAR message is wrong. But it actually looks  rather weird, sending always object ``#1`` after wind_set(WF_TOOLBAR). I've commneted that out now, and hope it does not break anything

**Comment by DavidGZ** [comment] 2021-10-01 17:44
Just in case something breaks, this is the commit where the code for sending that message was added:

eb75a10ac9236c3651ee71bc0941a7e97c335a14

**Comment by lpgb** [comment] 2021-11-05 17:57
I test a current snapshot and my app with a toolbar crashes at wind_set(30,...) when attaching the toolbar. Can this change be reverted?

**Comment by th-otto** [comment] 2021-11-05 18:07
Oops. I did that already, but forgot to push it. That's why this issue is open again. Done now.

**Comment by GokMasE** [comment] 2021-11-20 21:56
I tested xaaes.km (1.6.4. beta of Nov 19 2021 13:44 / 7.5.0) and did try it with the example posted by Lp earlier in this discussion.
Since the offending patch made earlier was reverted again, I am puzzled to see that I still get BUS ERROR when the mentioned test example tries to access the toolbar.

**Comment by lpgb** [comment] 2021-12-05 12:39
I just tried snapshot freemint-1-19-a694314f-02060.zip
Everything goes ok with my image viewer until I try to open a window with a toolbar, then it bus errors. 
Was that one line of code ever reverted back??

**Comment by th-otto** [comment] 2021-12-05 12:51
Yes, it was in https://github.com/freemint/freemint/commit/1a9b137d3f912eee23cc195554efcdc0ccd74a4b

**Comment by lpgb** [comment] 2021-12-05 13:18
That's strange, it was working prior to my report. It's working fine in NAES and MyAES. Something has changed.

**Comment by GokMasE** [comment] 2021-12-10 22:45
Confirmed, the toolbar support remains broken in XaAES.

**Comment by mikrosk** [comment] 2022-02-10 12:57
Just taken a look at the commits, Thorsten really reverted the code which he had changed earlier. I think you must have been testing some older XaAES which worked as described, there hasn't been any changes which could explain such crash.

**Comment by lpgb** [comment] 2022-02-10 15:52
Crashed with that one as well. So it appears toolbars are another victim of Helmut.

**Comment by xdelatour** [comment] 2023-03-31 21:53
Crash occurs because XaAES tries to read data from a NULL pointer. 

The following fix solves only the bus error:
[fix_wind_set_30.patch.txt](https://github.com/freemint/freemint/files/11127217/fix_wind_set_30.patch.txt)

**Comment by mikrosk** [comment] 2023-04-01 05:39
@xdelatour have you tested it also with @lpgb's ImgView? http://atari.gfabasic.net/htm/imgview.htm

**Comment by xdelatour** [comment] 2023-04-01 05:49
No. Only with tbtest. I don't have NVDI

**Comment by th-otto** [comment] 2023-04-01 06:00
Nice catch. I couldn't test it either but that was definitely a bug. Applied.

BTW, looking at the code it seems it doesn't handle the case where the same toolbar is installed again. If one is already installed, it will be removed?

**Comment by mikrosk** [comment] 2023-04-01 07:05
@lpgb can you test the latest snapshot with your ImgView, just to be sure? (then you can remove the warning at your web as well ;))

**Comment by lpgb** [comment] 2023-04-01 09:26
> @lpgb can you test the latest snapshot with your ImgView, just to be sure? (then you can remove the warning at your web as well ;))

Have the ozk branch installed where the toolbar works and don't really want to mess with it. Someone who actually that branch should test it. I'll glad removed the warning off the web page if someone confirms it's fixed.

**Comment by th-otto** [comment] 2023-04-01 13:03
Problem with testing this it that it requires both mint and NVDI. My only mint installation is running on aranym, and that uses fVDI.

**Comment by xdelatour** [comment] 2023-04-01 13:09
> Problem with testing this it that it requires both mint and NVDI. My only mint installation is running on aranym, and that uses fVDI.

Yes, NVDI is required, I added `cookie nvdi=$0501` in `fvdi.sys` but ImgView still crashes (probably because of incomplete support for v_transfer_bits freemint/fvdi#45).

**Comment by lpgb** [comment] 2023-04-01 16:21
> Problem with testing this it that it requires both mint and NVDI. My only mint installation is running on aranym, and that uses fVDI.

Fully understand not wanting to tamper with a working setup. I was told by someone that NVDI loaded over top fVDI allows ImgView to work. It's enough to get an image to load in a window with a toolbar. I think full screen mode still bombs, asking NVDI to fill in the gcbitmap structure itself seems to be fatal.

**Comment by mikrosk** [comment] 2023-04-01 18:18
We should educate people about the easiness of having parallel setups. :) Ok, I'll check it for you tomorrow.

**Comment by GokMasE** [comment] 2023-04-01 21:52
Thanks to xdelatour for your nice work - the toolbar crash with xaaes (current) indeed seems to be fixed.

I verified it by testing with ImgView (2023-03-08) under xaaes (current) from bootable build (2023-04-01):
![toolbar_working](https://user-images.githubusercontent.com/65512522/229315526-4b95e4a8-7648-468e-9988-d7a8a79f08f6.png)

**Comment by lpgb** [comment] 2023-04-02 04:49
> @lpgb can you test the latest snapshot with your ImgView, just to be sure? (then you can remove the warning at your web as well ;))

Warning reworded since a snapshot is required. Might have to force reload the page, server is bit iffy with updates.

**Comment by mikrosk** [comment] 2023-04-02 08:33
@GokMasE - thanks!

@lpgb - is this another bug or you are referring to the toolbar one: "XaAES's window handle management is broken and breaks ImgView. :o(" ... To me this sounds like ok, please use the snapshot but it's broken anyway. ;-)

**Comment by GokMasE** [comment] 2023-04-02 09:10
@mikrosk - there is indeed at least one other bug, although not as serious as the crash issue. If a window with a toolbar attached is iconified, any mouse clicks made will "bleed through" to the place where the toolbar should have been (if the iconified window would have sported such a thing).

I can post a separate issue on this particular problem tonight. I expect that filtering out mouse clicks to the toolbar when iconified would be quite trivial.

**Comment by mikrosk** [comment] 2023-04-02 12:10
@GokMasE that would be great, thank you. Having a separate issue with repro + description will definitely increase chances that somebody as our clever friend @xdelatour will be able to take a look and fix it. :)

**Comment by mikrosk** [comment] 2023-04-02 12:12
Fixed by https://github.com/freemint/freemint/commit/39859b2e5e7eb29fa686f02af077ce68972d8788, closing.

**Closed by mikrosk** 2023-04-02 12:12 UTC
Labels: xaaes

**Comment by lpgb** [comment] 2023-04-02 13:03
> @lpgb - is this another bug or you are referring to the toolbar one: "XaAES's window handle management is broken and breaks ImgView. :o(" ... To me this sounds like ok, please use the snapshot but it's broken anyway. ;-)

Apparently fixed a while back and I forgot to removed it. Comment updated on my site. It now notes the bleeding mouse clicks and missing borders instead. Gotta keep the pressure on. ;)

**Comment by xdelatour** [comment] 2023-04-04 05:28
> Fixed by [39859b2](https://github.com/freemint/freemint/commit/39859b2e5e7eb29fa686f02af077ce68972d8788), closing.

Only the crash is fixed. 

XaAES is always sending WM_TOOLBAR when a toolbar is attached to the window. I think we can remove the [faulty line](https://github.com/freemint/freemint/blob/master/xaaes/src.km/xa_wind.c#L969) again.

Btw, tos.hyp is really confusing. About wind_set(WF_TOOLBAR...), tos.hyp said "Activating a toolbar object results in the event WM_TOOLBAR."
The actual behaviour is "Click on TOUCHEXIT object inside a toolbar results in the event WM_TOOLBAR." (works also with EXIT object but XaAES never sends WM_TOOLBAR if the object is neither TOUCHEXIT nor EXIT). wind_set(WF_TOOLBAR...) must not send WM_TOOLBAR.

**Comment by th-otto** [comment] 2023-04-04 05:38
I once had already removed that line, but according to LP that caused his app to freeze, so i reverted that.

So tos.hyp is not really wrong, because (with that line) a message is also send when attaching the toolbar. But the main purpose of that message is of course to notify you about clicks.

**Comment by xdelatour** [comment] 2023-04-04 05:44
It would be nice to have preconfigured disk images for each system, to run with either Hatari and ARAnyM

**Comment by mikrosk** [comment] 2023-04-04 06:28
> Only the crash is fixed.

So how it is? Lonny states in the first post that his app is freezing due to the WM_TOOLBAR sending however now it doesn't anymore?

Then there was an attempt to fix it by Thorsten which caused a crash, so he reverted it back.

Now we have nothing crashing and nothing freezing so it looks good do me?

**Comment by lpgb** [comment] 2023-04-04 09:03
I call wind_create() and then wind_set(30,...) and there is where the confusion comes into play. The window is not open and displayed and yet a toolbar message #37 arrives and the app gets confused. Atari's AES 4.1 and NAES are ok with this, but had to add extra checks just for xaaes to filter out the message #37 arriving when the window isn't actually displayed. If comparing AES's it seems to be incorrect behavior, that's just my point view though.

**Comment by th-otto** [comment] 2023-04-04 09:15
But what about your comment in https://github.com/freemint/freemint/issues/230#issuecomment-946795496? If i remember correctly, that was tested with a version where that line was removed, and caused your app to freeze?

The crashes are a different thing and are hopefully fixed now.

**Comment by mikrosk** [comment] 2023-04-05 06:12
@GokMasE attached latest xaaes snapshot with the original Thorsten's commit: https://github.com/freemint/freemint/commit/661c7cfcd5cc73abc4b6f8cf41d3b45aed0c6efb

[xaaes.km.zip](https://github.com/freemint/freemint/files/11155721/xaaes.km.zip)

**Comment by GokMasE** [comment] 2023-04-05 19:43
Thanks to @mikrosk for the supplied test binary. 

With this version of XaAES and Lp's supplied test binary, there is no locking up when a window with a toolbar is opened.
Whether it was something wrong with the original test regarding this (when Thorsten first applied the patch) or whether something in the codebase has changed, I could only guess.

Sure seems to work ok now though, no probs opening several windows:

![xaes_and_imgview](https://user-images.githubusercontent.com/65512522/230185810-43ee0911-44dc-4e92-bd67-313253306c85.png)

**Comment by mikrosk** [comment] 2023-04-06 08:54
Hopefully definitely fixed in master.

**Comment by lpgb** [comment] 2023-04-07 13:53
Double checked gokmase findings, seems good now.
Can someone tweak this line at wind_set (30) in the toshyp: "Activating a toolbar object results in the event WM_TOOLBAR."
Either get rid of it as it sounds misleading or adjust it to something like:
"Activating a toolbar object results in event WM_TOOLBAR if a toolbar object is clicked."

**Comment by mikrosk** [comment] 2023-04-07 14:08
@lpgb: done, thanks for suggesting it.
