### ISSUE TITLE
XaAES always remaps textures into the default palette

### ISSUE THREAD

**Issue by mikrosk** [freemint/freemint#171] opened 2020-05-05 20:43 UTC
Joakim reported a very old (and still present) bug of XaAES, along with a pretty accurate analysis what is most likely going on:

> I can't help but noticing that I have the same palette
> problem (perhaps limited to 256 colours, since that is the only thing
> I am running here) with XaAES current version (daily build binaries
> from 2020-05-03)  as with my previously installed 2013 build of
> 1-19-cur. The problem is that the IMG textures for the GEM windows of
> XaAES are converted to wrong palette if NVDI is set in XAAES.CNF
> "palette = <name>". The IMG textures come out with colours all garbled
> up.
> 
> Since I am pretty sure that these IMG files are remapped by XaAES when
> it is launched, I am starting to suspect that XaAES is setting the
> palette specified in XAES.CNF as per "palette = <name>" but only
> *after* the IMG files have already been remapped.
> 
> So in essence, I think that the IMG files are remapped to the old
> Atari GEM palette (which seems to be the one present when XaAES is
> launching), and when XaAES later is issuing the switch to the NVDI
> palette, the IMG files are doomed to be looking wrong. And since
> texture image files are loaded/remapped during XAES startup sequence,
> it does not seem like they are affected by any other palette related
> entries to the xaaes config, like e.g. icn_pal_name. At least, nothing
> I tried editing seems to make a difference.

**Comment by th-otto** [comment] 2020-05-05 22:04
On Dienstag, 5. Mai 2020 22:44:11 CEST Miro Kropáček wrote:
> Joakim reported a very old (and still present) bug of XaAES, along with a 
pretty accurate analysis what is most likely going on:

Without looking into the code, i could totally imagine that his analysis is 
correct. But how do you want to handle that? There is no easy way to correctly 
display both a background image and other thing like gradients and color icons 
correctly, when they are using a totally different palette.

**Comment by mikrosk** [comment] 2020-05-06 06:10
I think he would be happy if we loaded the palette specified by `palette =` keyword first and then do the remapping and other stuff.

**Comment by th-otto** [comment] 2020-05-06 08:36
But are IMG file remapped at all? They have their own palette. If that is too different from the one later used, how do you want to do that, when only 256 colors are available?

**Comment by mikrosk** [comment] 2020-05-06 10:23
Well, that's the million dollar question. I'm not very familiar with xaaes internals, I would imagine it would use some dithering, actually I was under impression that this is what it's been doing the whole time. So we would just dither to different palette. But I may be totally wrong here.

**Comment by mikrosk** [comment] 2020-05-06 10:49
An important update: it used to work before ~2010, i.e. one could set nvdi palette and IMGs were reduced/approximated to that instead of the default one.

So this only confirms the theory that it seems that now the reduction/transformation step is happening before loading new palette.

**Comment by mikrosk** [comment] 2020-05-17 12:26
Oh yes, confirmed. Textures look like shit.

**Comment by GokMasE** [comment] 2021-02-05 11:38
The images used are for 100% sure remapped, in earlier builds (by ozk) there was info on this written to screen during start of XaAES. If I am allowed to guess, todays unfortunate remapping regression can have been introduced back when there were added several ways to specify which palette should be used for the system, which for rsc, etc. I am still convinced that the textures are being remapped to a hardcoded palette (rather than to the one specified in "palette = <name>" in XAES.CNF -if I am correct this probably would make an easy fix for any C-coder skilled enough to find their way around the xaaes sources) which seems to be the standard GEM palette - hence textures needs the system palette to be set to std GEM palette, or it will look wrong. Problem is, hardly anyone prefers GEM palette over NVDI palette today.

**Comment by GokMasE** [comment] 2021-10-01 07:42
Is there any chance at all that someone could have a closer look at this? I imagine anyone who wants to use XaAES in 256 colour mode will suffer from this - am I really the *only* person in the world to use XaAES in 256 colour mode as the standard setup? To use Mikro's precise words, "Textures look like shit".

(Since I am not able to follow C code, or any derivate there of, I can't investigate XaAES kernel code myself or else I most certainly would have - hopefully though, sending a proper bug report is the next best thing)

**Comment by mikrosk** [comment] 2021-10-01 08:26
I have it on my list of things to look at ... some day :) It really shouldn't be that hard to fix.

**Comment by GokMasE** [comment] 2021-10-01 09:02
> I have it on my list of things to look at ... some day :) It really shouldn't be that hard to fix.

If you do get to it at some point, I would be *enormously* grateful :)

There is in my mind a good chance that just setting the system palette to the one specified in "palette = " early, before any converting of gfx takes place, will do the trick.

As it is now, XaAES just seems to abruptly force the old GEM palette upon init, so one can't make it work with tweaking settings (other than actually USING the old GEM palette std as system palette, but that has other and quite unwanted side effects of course)

**Comment by mikrosk** [comment] 2021-10-02 13:18
Btw, if you don't specify any palette, i.e. leaving "palette = gem" commented out, the textures are garbled even without NVDI.

**Comment by mikrosk** [comment] 2021-10-02 16:48
Confirmed, it works in 1.17.0 (Dec 2010) and doesn't in 1.18.0 (Mar 2013). It has been caused by commit 43506c44, which had been ported into `freemint-1_18` by commit 89901aa9 merely a month before release... In usual Helmut's fashion, with huge numbers of changes and very little explanation. I'll try to come up with a fix.

**Comment by GokMasE** [comment] 2021-11-05 23:03
Just a quick follow-up to ask why this fix has not yet been merged?
(I very interested to help testing the very latest changes in FreeMiNT, but I sorely miss the palette bugfix in the current bootable builds)

**Comment by mikrosk** [comment] 2021-11-16 08:56
@th-otto do you see any hard-stopper there? While I completely agree that the fix isn't ideal (basically reverting to a poorly-understood-and-possibly-not-entirely-correct code), it is still a regression, i.e. removed code which used to work and now it doesn't. It has been tested in basic scenarios, in case we find something really wrong, we can always revert it.

**Comment by th-otto** [comment] 2021-11-16 09:30
Yes, go ahead. Its currently a bit too complicated for me to understand all scenarios, so if something goes wrong with the patch, we'll have to look at it again, but at leats now we now what was causing it ;)

**Closed** 2021-11-19 13:36 UTC
Labels: bug, xaaes

**Comment by mikrosk** [comment] 2021-11-19 13:38
@GokMasE go ahead and test / use / enjoy it in current master :)
