### ISSUE TITLE
USBTOOL.ACC - Text height issue under ST medium resolution

### ISSUE THREAD

**Issue by czietz** [freemint/freemint#106] opened 2019-02-03 12:28 UTC
When using USBTOOL.ACC under ST medium (640x200) resolution, the lines of text shown in USBTOOL.ACC overlap. See screenshot. Note: For the sake of taking a screen shot with Hatari, USBTOOL's source code was modified to show more than one line of text even in case no USB driver is loaded. However, the text overlap issue is also present on real hardware when actual USB devices are connected.

My VDI knowledge is rather rudimentary, but it seems to me that the wrong font size is chosen here. I would expect the list of devices using the same font size as the info line ("0 device").

![grab0006](https://user-images.githubusercontent.com/9830685/52176753-4ca6a980-27b7-11e9-9ddd-bb614ad53f60.png)

PS: In ST low (320x200), the window is to wide to be usable; but from what can be seen, the same issue applies there as well.

**Comment by czietz** [comment] 2019-02-03 12:31
PPS: This is with TOS 2.06 but it looks the same with, e.g., EmuTOS.

**Comment by Perdrix24** [comment] 2019-02-03 13:59
OK, I added this issue to my things to do list.

**Comment by czietz** [comment] 2019-02-03 15:33
I think, this is (at least in part) an issue with GEMLIB. In its v_opnvwk binding, it sets the text height to 13: 
https://github.com/freemint/gemlib/blob/d57cebf1d47d9d16507c0530eed4665bcb6ea160/v_opnvwk.c#L47

You could work around that by querying the actual font height, e.g. with vqt_attributes. Then the lines would not overlap anymore. But they would still use this rather ugly scaled font.

I wonder why this was done in GEMLIB.

**Comment by th-otto** [comment] 2019-02-03 16:56
On Sonntag, 3. Februar 2019 16:33:11 CET czietz wrote:
> I wonder why this was done in GEMLIB.

I think because of the comments above those settings:

> some VDI doesn't have the same default parameters. Here is a fix 

However, blindly setting the default text height (and maybe also the marker 
height) was a bad idea. I think that should be removed.

**Comment by czietz** [comment] 2019-02-04 09:59
> However, blindly setting the default text height (and maybe also the marker height) was a bad idea. I think that should be removed.

I would open a ticket with GEMLIB; but I fear that removing that line might break other software that currently assumes that text height = 13 is set.

**Comment by DavidGZ** [comment] 2019-02-04 10:21
As GEMLIB is a static library software won't break until is not recompiled, if it's possible to recompile those applications this means that source is available and the issue could be fixed in the right place, but I recognize that we can give some hard time to software authors if they are not aware of this change in GEMLIB.

**Comment by th-otto** [comment] 2019-02-04 10:34
I doubt that it would break any software. Applications that don't set the text height would suffer from the same problem, using a too large font in medium resolution, so it would rather fix than break them. Others that explicitly set the text height  won't notice any change.

**Comment by czietz** [comment] 2019-02-06 17:55
I've opened an issue in GEMLIB: https://github.com/freemint/gemlib/issues/11.
@Perdrix24: Feel free to either work around this issue in USBTOOL or to close the issue here and wait for the GEMLIB fix.

**Comment by Perdrix24** [comment] 2019-02-06 20:08
I prefer to close the issue here and wait for the GEMLIB fix. The code I use in USBTOOL is the same that I used for CDISO (compiled with PureC) and it works there in medium rez.

**Comment by Perdrix24** [comment] 2019-02-07 21:02
Not sure if I can close an issue, or don't know how.

**Comment by czietz** [comment] 2019-02-07 21:11
I can so, though. You probably saw the GEMLIB was fixed. You'd probably have to trigger a rebuild of USBTOOL.ACC, though.

**Comment by czietz** [comment] 2019-03-18 21:00
Sorry, my assumption was wrong: simply fixing the issue in GEMLIB's Git repository won't automatically fix USBTOOL.ACC upon a rebuild. The wrong text height still persists even with the snapshot build from March 14th.

As far as I have found out, Travis uses a pre-built GEMLIB from @vinriviere's server. I guess, that needs to be updated as well.

**Comment by th-otto** [comment] 2019-03-19 02:27
Yes, you have to wait until Vincents repo has been updated. Same happens with changes to mintlib. Maybe, for snapshot builds, we should use something else?

**Comment by mikrosk** [comment] 2019-03-19 07:24
There's nothing which prevents us from using wget + tar xzf instead of apt-get for Travis builds, it just isn't so clean and elegant. Plus you would need to take care of restarting (freemint) builds manually in such case as there is no dependency tracking possible across github repos (unfortunately).

**Comment by th-otto** [comment] 2019-03-19 07:52
Only problem i see is to figure out the commit-id and filename of the last snaphot build of gemlib/mintlib. Also it might help to change the identifier (those __Ident_  strings that are compiled into the lib) of those builds, so in case someone tries to figure out which snapshot indtroduced a regression, he can also figure out the corresponding libraries in use. That would also make sense for the apt packages, since the library versions haven't changed for years.

**Comment by vinriviere** [comment] 2019-03-19 12:19
Ok, I will update the Ubuntu cross-tools. Indeed, the GemLib is rather outdated there.

**Comment by th-otto** [comment] 2019-03-19 12:35
Thats nice. But it is not the root of the problem. Nobody expects you to update the archives after every commit. If something has been changed in gemlib or mintlib to fix a problem somewhere else, there is currently no way to provide snapshot versions of the fixed version, you have to compile it yourself.

**Comment by mikrosk** [comment] 2019-03-19 16:04
Actually, I have done a few experiments with Bintray's opkg repositories. It works quite all right, the only annoyance is that you have to prepare/compile `opkg` binary by yourself as it is (naturally) not present on a Debian-based distro (what Travis is).

So it is possible to compile gemlib in travis, upload it to bintray, it automatically updates its opkg repository and you can install it with something like `opkg install gemlib` during freemint's build. It tracks dependencies and all. Of course, the same can be done for deb packages (and few others) but I feel opkg has the right amount of complexity, features and simplicity to be used on our platform.

**Comment by th-otto** [comment] 2019-03-19 16:14
I'm not sure. The builds from travis (or any CI) are just snapshots. They should not be treated as releases. Also, that still leaves the question what version "opkd install" will install, unless you choose to not include any version number and/or commit id in the package.

**Comment by mikrosk** [comment] 2019-03-19 16:28
I am sure that is why I mention it. :) You can have various so called streams, so you can choose whether you want release, nightly etc versions.

**Comment by Perdrix24** [comment] 2019-10-29 23:30
Thanks for fixing it. I didn't think it could be a problem in usbtool, because I took the code from CD InScriptOr (from CD Writer Suite) that I co-authored,  that didn't display this problem. Good job, now the display is nice!

**Closed** 2019-11-01 14:18 UTC
