### ISSUE TITLE
Falcon Alternate Magnum Ram ...

### ISSUE THREAD

**Issue by franklukas** [freemint/freemint#132] opened 2019-11-12 18:42 UTC
1-19-C64 and -923 works not longer on a Atari 4MB Falcon with a Magnum Falcon 6MB Alternate Ram Card. The MiNT Kernel boots up and stop working at "Installing BIOS keyboard table ..." ...

**Comment by DavidGZ** [comment] 2019-11-12 19:25
Could you test please the previous snapshot to -923?

https://dl.bintray.com/freemint/freemint/snapshots/1-19-4f001fdd/:freemint-1-19-4f0-02060-tt_falcon_clones.zip

**Comment by franklukas** [comment] 2019-11-12 19:45
4f0 works fine with the magnum altram card ...

**Comment by DavidGZ** [comment] 2019-11-13 09:05
This is not related to changes done in the commit 4d0b88b113eea361b287c974946f4d4b89454ef2, but again with this issue here https://github.com/freemint/freemint/issues/92#issuecomment-421922818
There is something really wrong with 030 kernels, I suspect about the MMU code. It depends where some kernel code is loaded in memory the system boots stop. Frank is you add or remove some program in the AUTO folder before the kernel is loaded boot will continue without problems.

**Comment by mikrosk** [comment] 2019-11-13 09:15
Oh wow, this really _is_ scary. Just to explain to @franklukas, all the changes past 4d0b88b are xaaes related so there's no way the kernel boot can hang because of it.

The trouble is that we don't have a stable repro. #92 happens only on my CT2 Falcon (which is still in pieces but moving toward fixing it again) and this issues happens on the Magnum card which is again a hardware not spread enough to test it.

**Comment by DavidGZ** [comment] 2019-11-13 09:31
> 
> The trouble is that we don't have a stable repro. #92 happens only on my CT2 Falcon (which is still in pieces but moving toward fixing it again) and this issues happens on the Magnum card which is again a hardware not spread enough to test it.

I can reproduce it right now with my Falcon, it has Centek RAM card (latest kernel), but this is independent of the card used because the first time I hit this issue I thought that was RAM related issue so I installed the original Falcon's RAM card and the problem persisted.

**Comment by th-otto** [comment] 2019-11-13 09:31
I wonder whether that really happens only with  030 kernels, or also with 040/060

**Comment by th-otto** [comment] 2019-11-13 09:35
BTW, somewhere during memory initialization, MiNT tries to detect the memory regions that are already in use, before installing the MMU tables. Dependencies on programs loaded before MiNT sounds like something is going wrong there.

**Comment by DavidGZ** [comment] 2019-11-13 09:36
> I wonder whether that really happens only with 030 kernels, or also with 040/060

I've never seen this issue with the Falcon in 060 mode, it's always when it's in 030 mode.
When the hardware has FastRAM where is the kernel loaded?

**Comment by mikrosk** [comment] 2019-11-13 09:39
OK, I'll test it on my Falcon today.

And I second David, I have never seen this issue in 060 mode. But then again, 060 usually means heaps of memory, so this may scramble the problem.

**Comment by mikrosk** [comment] 2019-11-13 09:39
> When the hardware has FastRAM where is the kernel loaded?
Surely into fast ram.

**Comment by mikrosk** [comment] 2019-11-13 17:19
Hate to say that but "works for me". Unpacked c64a6a47 snapshot on C: and rebooted:

- works in 060
- works in 030
- with and without NVDI (i.e. without anything else in AUTO)
- with and without MP
- even lowered the debug level to ALERT only

@DavidGZ are you sure you don't have something else coming in the boot process? Otherwise I can think of only different SIMM timing = different speed but that feels way too sensible to be the case.

**Comment by DavidGZ** [comment] 2019-11-13 18:07
Sorry I was not clear that I can trigger the problem with the latest kernel in my regular Falcon installation, not running the pure snapshot.

Before the kernel in memory are loaded:

XBOOT III
CALVINO
DRVIN
SCC
NVDI

If I remove any of the above mentioned programs the boot process ends OK.
Memory protection doesn't affect the problem.

**Comment by mikrosk** [comment] 2019-11-13 18:10
Can you make a copy and try in Hatari? That would help A LOT.

**Comment by franklukas** [comment] 2019-11-13 18:17
My Auto Folder are empty except the magnum030.prg driver program.

The Atari Falcon is a 4MB Version. With the magnum card I have plus 6MB alternate ram. In total 10MB ram.

The 6MB magnum fastram are not over the 16MB ST ram area !?!

**Comment by DavidGZ** [comment] 2019-11-13 18:19
Yes, I'm trying with Hatari now :-), the problem can be replicated. I'm learning about Hatari debug facilities, I've never used them before.

For now before the boot stops, this is shown in Hatari console:

Illegal instruction: 4b50 at 001C23E0 -> 00186DA2
Illegal instruction: 4b50 at 001C23E0 -> 00186DA2
Illegal instruction: 4b50 at 001C23E0 -> 00186DA2
Illegal instruction: 4b50 at 001C23E0 -> 00186DA2
Illegal instruction: 4b50 at 001C23E0 -> 00186DA2
Illegal instruction: 4b50 at 001C23E0 -> 00186DA2
Illegal instruction: 4b50 at 001C23E0 -> 00186DA2
Illegal instruction: 4b50 at 001C23E0 -> 00186DA2
Illegal instruction: 4b50 at 001C23E0 -> 00186DA2
Illegal instruction: 4b50 at 001C23E0 -> 00186DA2
Illegal instruction: 4b50 at 001C23E0 -> 00186DA2
Illegal instruction: 4b50 at 001C23E0 -> 00186DA2
Illegal instruction: 4b50 at 001C23E0 -> 00186DA2
Illegal instruction: 4b50 at 001C23E0 -> 00186DA2
Illegal instruction: 4b50 at 001C23E0 -> 00186DA2
Illegal instruction: 4b50 at 001C23E0 -> 00186DA2
Illegal instruction: 4b50 at 001C23E0 -> 00186DA2
Illegal instruction: 4b50 at 001C23E0 -> 00186DA2
Illegal instruction: 4b50 at 001C23E0 -> 00186DA2
Illegal instruction: 4b50 at 001C23E0 -> 00186DA2

It looks like while the boot is halted the CPU is running continuously the function post_sig() from signal.c file

**Comment by mikrosk** [comment] 2019-11-13 18:50
Just to be sure - does it behave identically? I mean works if some PRG is disabled, doesn't if all are enabled?

If so, feel free to post your image, more eyes -> better chance to catch it. ;-) (IIRC @th-otto has debugged his 030 MMU code with Hatari).

**Comment by DavidGZ** [comment] 2019-11-14 08:19
> Just to be sure - does it behave identically? I mean works if some PRG is disabled, doesn't if all are enabled?
> 

Yes, if I disable some AUTO PRGs the boot works, although I'm having some weird issues with hatari, Xboot can't disable some of the programs and can't save the configuration.

> If so, feel free to post your image, more eyes -> better chance to catch it. ;-) (IIRC @th-otto has debugged his 030 MMU code with Hatari).

OK, but I think I need to clean it up a bit, I don't know if I'm ready to show publicly my private chaos. :-) Where would be a good place to post a 4GB image?

**Comment by mikrosk** [comment] 2019-11-14 08:24
Just delete the other partitions (or wipe them with HD Driver so they are full of zeroes), pack them and it should be quite small. Github allows attaching files here, too. If it's still too big, I guess just upload it to some sharing service.

**Comment by DavidGZ** [comment] 2019-11-14 19:40
@mikrosk the image tidy up was not going straightforward and I decided to spent the time debugging instead of solving the small issues I was having, besides I wanted to take this opportunity to learn about debugging with Hatari.

As far as I've seen the problem is in the function ccw_set in cpu.S which is called twice from init() (init.c)

https://github.com/freemint/freemint/blob/43d215a830ff11192e4ad225fe5a5d634f8cc6a9/sys/arch/cpu.S#L161-208

The second time is called the routine returns to a bogus address, I've checked the stack before "rts" is executed and the correct address is there but "rts" still returns to some random address. If you look at the routine, before caches are enabled they're invalidated or flushed only for the 040 and 060, the comments states that for the 030 is not necessary. So my guess is that this is not true and for some reason when the 030 CPU pulls the return address from the stack the value kept in the cache is wrong. I can't explain why this happens sometimes depending where in memory is the kernel.

Below you can see that before calling "rts" the address in the stack is 0x00159934 but it jumps to 0x001c23c2

```
CPU=$1864f6, VBL=1454, FrameCycles=42420, HBL=41, LineCycles=436, DSP=N/A
$001864f6 : 4280                               clr.l     d0
> r
  D0 00003111   D1 00002404   D2 00180004   D3 00000000 
  D4 00000000   D5 00000000   D6 00000000   D7 00000000 
  A0 001B5A3C   A1 00186690   A2 0018647A   A3 00159464 
  A4 0015948E   A5 001594C2   A6 0018A148   A7 001C2600 
USP  001C2606 ISP  001C2600 SFC  00000000 DFC  00000000 
CACR 00003111 VBR  00000000 CAAR 00186FE4 MSP  00000000 
T=00 S=1 M=0 X=1 N=1 Z=0 V=0 C=1 IMASK=3 STP=0
SRP: 0 CRP: 8000000200000700
TT0: 017E8107 TT1: 807E8507 TC: 80F04445
Prefetch 001864f8 4e754a79 (2) 4e75 (1) 4a79 (1) 4e75 (2)
001864F6 4280                     CLR.L D0
Next PC: 001864f8
> disasm $1c2600
$001c2600 : 0015 9934                          ori.b     #$34,(a5)
$001c2604 : 0000 c567                          ori.b     #$67,d0
$001c2608 : 0000 c57f                          ori.b     #$7f,d0
$001c260c : 0000 0000                          ori.b     #0,d0
$001c2610 : 0000 c57f                          ori.b     #$7f,d0
$001c2614 : 0018 117d                          ori.b     #$7d,(a0)+
$001c2618 : 0018 119f                          ori.b     #$9f,(a0)+
$001c261c : 0018 103e                          ori.b     #$3e,(a0)+
$001c2620 : 0000 0000                          ori.b     #0,d0
$001c2624 : 0000 0000                          ori.b     #0,d0
$001c2628 : 0000 0000                          ori.b     #0,d0
$001c262c : 0000 0000                          ori.b     #0,d0
$001c2630 : 0000 0000                          ori.b     #0,d0
$001c2634 : 0018 f5ac                          ori.b     #$ac,(a0)+
$001c2638 : 0018 bc50                          ori.b     #$50,(a0)+
$001c263c : 00dd                               DC.W      $00dd
$001c263e : a6c6                               linea     #$6c6
$001c2640 : 0000 0000                          ori.b     #0,d0
$001c2644 : 0000 0000                          ori.b     #0,d0
$001c2648 : 0000 0000                          ori.b     #0,d0
$001c264c : 0000 0000                          ori.b     #0,d0
$001c2650 : 001c 265c                          ori.b     #$5c,(a4)+
$001c2654 : 0000 0000                          ori.b     #0,d0
$001c2658 : 0000 0000                          ori.b     #0,d0
$001c265c : 004a                               DC.W      $004a
$001c265e : 0000 0013                          ori.b     #$13,d0
$001c2662 : a8f8                               linea     #$8f8
$001c2664 : 0008                               DC.W      $0008
$001c2666 : 7d70                               DC.W      $7d70
$001c2668 : 0000 0000                          ori.b     #0,d0
$001c266c : 0000 0000                          ori.b     #0,d0
$001c2670 : 0000 0000                          ori.b     #0,d0
$001c2674 : 0000 0000                          ori.b     #0,d0
$001c2678 : 0000 0000                          ori.b     #0,d0
$001c267c : 0000 0000                          ori.b     #0,d0
$001c2680 : 0000 0000                          ori.b     #0,d0
$001c2684 : 0000 0000                          ori.b     #0,d0
$001c2688 : 0000 0000                          ori.b     #0,d0
$001c268c : 0000 0000                          ori.b     #0,d0
> s

CPU=$1864f8, VBL=1454, FrameCycles=42420, HBL=41, LineCycles=436, DSP=N/A
$001864f8 : 4e75                               rts       
> disasm $1c2600
$001c2600 : 0015 9934                          ori.b     #$34,(a5)
$001c2604 : 0000 c567                          ori.b     #$67,d0
$001c2608 : 0000 c57f                          ori.b     #$7f,d0
$001c260c : 0000 0000                          ori.b     #0,d0
$001c2610 : 0000 c57f                          ori.b     #$7f,d0
$001c2614 : 0018 117d                          ori.b     #$7d,(a0)+
$001c2618 : 0018 119f                          ori.b     #$9f,(a0)+
$001c261c : 0018 103e                          ori.b     #$3e,(a0)+
$001c2620 : 0000 0000                          ori.b     #0,d0
$001c2624 : 0000 0000                          ori.b     #0,d0
$001c2628 : 0000 0000                          ori.b     #0,d0
$001c262c : 0000 0000                          ori.b     #0,d0
$001c2630 : 0000 0000                          ori.b     #0,d0
$001c2634 : 0018 f5ac                          ori.b     #$ac,(a0)+
$001c2638 : 0018 bc50                          ori.b     #$50,(a0)+
$001c263c : 00dd                               DC.W      $00dd
$001c263e : a6c6                               linea     #$6c6
$001c2640 : 0000 0000                          ori.b     #0,d0
$001c2644 : 0000 0000                          ori.b     #0,d0
$001c2648 : 0000 0000                          ori.b     #0,d0
$001c264c : 0000 0000                          ori.b     #0,d0
$001c2650 : 001c 265c                          ori.b     #$5c,(a4)+
$001c2654 : 0000 0000                          ori.b     #0,d0
$001c2658 : 0000 0000                          ori.b     #0,d0
$001c265c : 004a                               DC.W      $004a
$001c265e : 0000 0013                          ori.b     #$13,d0
$001c2662 : a8f8                               linea     #$8f8
$001c2664 : 0008                               DC.W      $0008
$001c2666 : 7d70                               DC.W      $7d70
$001c2668 : 0000 0000                          ori.b     #0,d0
$001c266c : 0000 0000                          ori.b     #0,d0
$001c2670 : 0000 0000                          ori.b     #0,d0
$001c2674 : 0000 0000                          ori.b     #0,d0
$001c2678 : 0000 0000                          ori.b     #0,d0
$001c267c : 0000 0000                          ori.b     #0,d0
$001c2680 : 0000 0000                          ori.b     #0,d0
$001c2684 : 0000 0000                          ori.b     #0,d0
$001c2688 : 0000 0000                          ori.b     #0,d0
$001c268c : 0000 0000                          ori.b     #0,d0
> s

CPU=$1c23c2, VBL=1454, FrameCycles=42444, HBL=41, LineCycles=460, DSP=N/A
$001c23c2 : 001c 23da                          ori.b     #$da,(a4)+
```

**Comment by mikrosk** [comment] 2019-11-14 19:48
Nice find! I haven't inspected the code thoroughly but if I understand it right, it's really wrong! This is not how you set new CACR! The correct setting looks like this: https://sourceforge.net/p/mxplay/code/HEAD/tree/trunk/asm_routines.S#l91

As you can guess, I'd had my share of trouble with caches in mxPlay, too. :) Can you try to clear the cd/ci bits whether it still crashes?

**Comment by DavidGZ** [comment] 2019-11-15 10:18
@mikrosk thanks for the link!

If I invalidate the caches for the 030 the boot doesn't halt, but we can't be 100% that this solved the problem because of the nature of it, the kernel has changed its size so this could have been the reason why the boot is OK now.

So to explain the logic of this cache theory. MiNT has a function ccw_set() to abstract the cache settings from the hardware. This function tests before returning if caches are going to be enable of disable, if they're going to be enable the function invalidate the caches, if they are going to be disable the function flushes the caches, the problem is that it only does this when we're on a 040 or 060 CPU, the argument is because the 030 is not a copyback cache, I think this argument is right when we are going to disable the caches so it's not necessary to flush them in the 030, but it's not right when we are going to enable them, in this case we still need to invalidate them.

**Comment by th-otto** [comment] 2019-11-15 10:29
When you are going to enable them, and they were disabled before, there is no need to invalidate them. That might also apply to 040/060.

**Comment by DavidGZ** [comment] 2019-11-15 10:58
>When you are going to enable them, and they were disabled before, there is no need to invalidate them. That might also apply to 040/060.

If this is true I don't know how to explain this behaviour below.

$001c2600 is the stack address when we'll return from the second instance of ccw_set() in init().
Just before we disable the caches the content of $001c2600 is 001c 23c2
```
CPU=$1864ee, VBL=1315, FrameCycles=4264, HBL=4, LineCycles=168, DSP=N/A
$001864ee : 4e7b 0002                          movec     d0,cacr

> disasm $1c2600
$001c2600 : 001c 23c2                          ori.b     #$c2,(a4)+
```
This is before we enable the caches again, before "rts" A7 is $001c2600 and points to $00159934



```
CPU=$1864ee, VBL=1315, FrameCycles=41908, HBL=40, LineCycles=948, DSP=N/A
$001864ee : 4e7b 0002                          movec     d0,cacr

> s
CPU=$1864f2, VBL=1315, FrameCycles=41940, HBL=40, LineCycles=980, DSP=N/A
$001864f2 : 4cdf 0706                          movem.l   (sp)+,d1-d2/a0-a2

> s
CPU=$1864f6, VBL=1315, FrameCycles=41980, HBL=40, LineCycles=1020, DSP=N/A
$001864f6 : 4280                               clr.l     d0

> r
  D0 00003111   D1 00002404   D2 00180004   D3 00000000 
  D4 00000000   D5 00000000   D6 00000000   D7 00000000 
  A0 001B5A3C   A1 00186690   A2 0018647A   A3 00159464 
  A4 0015948E   A5 001594C2   A6 0018A148   A7 001C2600 
USP  001C2606 ISP  001C2600 SFC  00000000 DFC  00000000 
CACR 00003111 VBR  00000000 CAAR 00186FE4 MSP  00000000 
T=00 S=1 M=0 X=1 N=1 Z=0 V=0 C=1 IMASK=3 STP=0
SRP: 0 CRP: 8000000200000700
TT0: 017E8107 TT1: 807E8507 TC: 80F04445
Prefetch 001864f8 4e754a79 (2) 4e75 (1) 4a79 (1) 4e75 (2)
001864F6 4280                     CLR.L D0
Next PC: 001864f8

> disasm $1c2600
$001c2600 : 0015 9934                          ori.b     #$34,(a5)

> s
CPU=$1864f8, VBL=1315, FrameCycles=41980, HBL=40, LineCycles=1020, DSP=N/A
$001864f8 : 4e75                               rts       

```
But we end up in $001c23c2 which was the value in $001c2600 before we disabale the caches
```
> s

CPU=$1c23c2, VBL=1315, FrameCycles=42004, HBL=41, LineCycles=20, DSP=N/A
$001c23c2 : 001c 23da                          ori.b     #$da,(a4)+
```

**Comment by mikrosk** [comment] 2019-11-15 11:00
@DavidGZ there's an easy test to do - replace my code (the one setting CI/DI) with NOPs, exactly the same size. If it's not halted with NOPs ->  you are right, if it is -> the fix really works. :)

**Comment by DavidGZ** [comment] 2019-11-15 11:01
>f you fix that, and it solves your problem, it would be interesting to know whether that also has an influence on the memory protection bug on CT60

Yes, it would be great if somebody could test it. I think you mean the CT2 which is the one which has a 030

**Comment by mikrosk** [comment] 2019-11-15 11:02
> If you fix that, and it solves your problem, it would be interesting to know whether that also has an influence on the memory protection bug on CT60

@th-otto refresh my memory, which bug is that?

**Comment by th-otto** [comment] 2019-11-15 11:10
Yes i mean CT2. Mint with memory-protection enabled on 030, after the fixes for TT-RAM >= 256MB

**Comment by DavidGZ** [comment] 2019-11-15 11:10
> @DavidGZ there's an easy test to do - replace my code (the one setting CI/DI) with NOPs, exactly the same size. If it's not halted with NOPs -> you are right, if it is -> the fix really works. :)

Good idea! My changes were more complicated that your code at the end. But this evening to test that this was the real solution I will test with your code.

Those are my changes. If this is finally the solution I'd like that before I commit the patch others take a look at the code.

```

diff --git a/sys/arch/cpu.S b/sys/arch/cpu.S
index 4572172c..d52af100 100644
--- a/sys/arch/cpu.S
+++ b/sys/arch/cpu.S
@@ -225,10 +225,10 @@ _ccw_set:
 	lea	-20(sp),sp
 	movem.l	d1-d2/a0-a2,(sp)
 #else
-	beq.s	clq
+	beq	clq
 	movem.l	d1-d2/a0-a2,-(sp)
 #endif
-	bsr.s	_ccw_get		// get the current CCW
+	bsr	_ccw_get		// get the current CCW
 	move.l	d0,-(sp)		// save it for later reference
 	move.l	28(sp),d1		// user specified CCW
 	move.l	32(sp),d2		// user specified CCM
@@ -269,14 +269,33 @@ no_icache:
 	btst	#1,d2			// same as above, but for the data cache
 	beq.s	dc_off
 	btst	#1,d1
-	bne.s	lt040
+	bne.s	write_cacr
 	dc.w	0xF458			// cinva dc
 	bra.s	lt040
 dc_off:
 	btst	#1,d1
-	beq.s	lt040
+	beq.s	write_cacr
 	dc.w	0xF478			// cpusha dc
-lt040:
+lt040:					// Although 030 has writethrough cache we still
+#ifdef __mcoldfire__			// need to inavlidate caches before enable them
+	move.w	_mcpu+2,a0
+	cmpa.l	#30,a0			// it's a 68030?
+#else
+	cmpi.w	#30,_mcpu+2		// it's a 68030?
+#endif
+	blt.s	write_cacr
+	btst	#0,d2			// 030 instruction cache going to be enabled?
+	beq.s	inv_030dc
+	btst	#0,d1			// if yes, is it currently disabled?
+	bne.s	inv_030dc
+	or.l	#0b000000001000,d0	// ci bit (clear i-cache)
+inv_030dc:
+	btst	#1,d2			// same as above, but for the data cache
+	beq.s	write_cacr
+	btst	#1,d1
+	bne.s	write_cacr
+	or.l	#0b100000000000,d0	// cd bit (clear d-cache)
+write_cacr:
 	movec	d0,cacr			// write CACR
 #ifdef __mcoldfire__
 	movem.l	(sp),d1-d2/a0-a2
```

**Comment by th-otto** [comment] 2019-11-15 11:14
Instead of explicitly using beq.s etc you can also use jbeq (gas pseudo opcodes).  That will optimize be optimized to short branches if possible. Just be careful with branches to the following instructions, older gas versions have a bug and will incorrectly assemble them to short branches with zero offset, which is essentially a word branch.

**Comment by DavidGZ** [comment] 2019-11-15 16:46
> @DavidGZ there's an easy test to do - replace my code (the one setting CI/DI) with NOPs, exactly the same size. If it's not halted with NOPs -> you are right, if it is -> the fix really works. :)

Replacing your code with NOPs makes the booting succeed too :-(

**Comment by DavidGZ** [comment] 2019-11-15 16:47
> Instead of explicitly using beq.s etc you can also use jbeq (gas pseudo opcodes). That will be optimized to short branches if possible. Just be careful with branches to the following instructions, older gas versions have a bug and will incorrectly assemble them to short branches with zero offset, which is essentially a word branch.

OK! thanks for the tip.

**Comment by mikrosk** [comment] 2019-11-15 16:51
Damn... You can always try a minimalistic version, i.e. forget all the logic and add only one 'or' to d0 - and check that with and without NOPs.

**Comment by DavidGZ** [comment] 2019-11-15 17:12
> Damn... You can always try a minimalistic version, i.e. forget all the logic and add only one 'or' to d0 - and check that with and without NOPs.

This is what I did, your code only have one "or" to d0, unless I didn't understand what you meant with "forget all the logic".

One thing I could try is adding "packets" of 3 NOPs (to have the same size, one OR = 3 NOPs) until the boot fails again, and then exchange one of those "packets" with the "or" to invalidate the data cache, and see if this fix the failing boot.

**Comment by mikrosk** [comment] 2019-11-15 17:22
By that logic I meant your whole patch. :) So if you changed just that one OR then I agree, the 3-NOP chunks sounds like a good idea.

**Comment by DavidGZ** [comment] 2019-11-16 20:04
> By that logic I meant your whole patch. :) So if you changed just that one OR then I agree, the 3-NOP chunks sounds like a good idea.

I tried adding some NOPs in groups of three but I can't make the boot fail again.

In the meantime I saw this in the 68030 user manual:
"Disabling the data cache does not flush the entries. If  it  is  enabled again, the previously valid entries remain  valid and can be used"

So with that affirmation plus the results in the debugging logs I posted above I'm 95% sure that the cache not being invalidated is the reason for this issue. In any case the patch should be committed although the problem is elsewhere.

I was trying to understand why the size of the kernel or where it is loaded in memory makes to arise this issue, I think it's clear that the size of the kernel or the applications run before it determines the  position of the stack and more precisely the position in the stack of the return address for the "rts" instruction. When the boot fails the return address is in 0x001C2600 which is in a 16 bytes boundary which is the size of the m68k cache line and in a 256 bytes boundary which is the size of the data cache in the 030, perhaps it's coincidence but I think is a hint. When the cache is enabled again it's in burst mode, if I understood correctly in this mode cache entries are filled as entire cache lines (16 bytes).

Does anybody know how can increase the kernel size with accuracy? I've been trying to put some dummy space in the .data section with the directive ".ds.b xxx" but this doesn't work very well.

**Comment by th-otto** [comment] 2019-11-16 22:14
On Samstag, 16. November 2019 21:04:22 CET DavidGZ wrote:
> Does anybody know how can increase the kernel size with accuracy?

I think the easiest way is to put some nops in arch/startup.S

**Comment by DavidGZ** [comment] 2019-11-17 08:31
> >On Samstag, 16. November 2019 21:04:22 CET DavidGZ wrote: Does anybody know how can increase the kernel size with accuracy?
> I think the easiest way is to put some nops in arch/startup.S

I tried that but in arch/cpu.S and for some reason if I add more than 184 bytes and extra byte is added to the size, also happens this if I use the ".ds.b" directive method in the .data section.
With your suggestion works fine, adding the nops in arch/startup.S did the trick. Thanks!

**Comment by DavidGZ** [comment] 2019-11-17 08:44
My suspicious was correct, if the return address for the "rts" is located in a 256 bytes boundary the boot fails. I've forced to be now in 0x001C2700 instead 0x001C2600 and boot fails again, then I removed 4 nops (8 bytes) and I added the code to invalidate the caches so the return address keeps located in 0x001C2700 and the boot succeeded.
Contrary from what I'd have expected If the return address is in a 16 byes boundary (cache line size) it does not affect the result.

**Comment by mikrosk** [comment] 2019-11-17 10:49
The 16-bytes scenario is easily explained, the burst mode is not supported on standard Falcon.

I'm not at home now but anyway - great work, David!

**Comment by DavidGZ** [comment] 2019-11-17 18:33
I've just pushed the fix for this issue. I modified a little bit the patch above because I didn't thought about the 68020 and the ColdFire (BTW ccw_set() does nothing on this CPU)

**Comment by mikrosk** [comment] 2019-11-25 07:40
Hey @franklukas, does the new kernel work for you?

**Comment by franklukas** [comment] 2019-12-13 20:46
I try the 1-19-Cur 030 9f2ed80b Version and it do not work well. 

pid 0 (MiNT): assert (´cwd´)failed at line 451 of ../dosdir.c
Fatal error ...

**Comment by DavidGZ** [comment] 2019-12-14 11:26
> I try the 1-19-Cur 030 [9f2ed80](https://github.com/freemint/freemint/commit/9f2ed80bfebfe3d112a00d8588f579120fba37c1) Version and it do not work well.
> 
> pid 0 (MiNT): assert (´cwd´)failed at line 451 of ../dosdir.c
> Fatal error ...

I can't replicate it. Do you get the same error every time you boot?

Could you please test:
https://dl.bintray.com/freemint/freemint/snapshots/1-19-1fda5cd1/:freemint-1-19-1fd-02060-tt_falcon_clones.zip

**Comment by franklukas** [comment] 2019-12-14 16:18
1fd works fine ...

It is a pitty that 10MB of Ram are not enough for MiNT/XaAES !

**Comment by DavidGZ** [comment] 2019-12-14 16:38
> 1fd works fine ...
> 

OK, thanks for the feedback. Where during the boot do you get the error with version 9f2ed80

> It is a pitty that 10MB of Ram are not enough for MiNT/XaAES !

**Comment by franklukas** [comment] 2019-12-14 16:45
pid 0 (MiNT): assert (´cwd´)failed at line 451 of ../dosdir.c
Fatal error. You must reboot the system.

.. is with the 9f2 every time !

**Comment by DavidGZ** [comment] 2019-12-14 16:56
> pid 0 (MiNT): assert (´cwd´)failed at line 451 of ../dosdir.c
> Fatal error. You must reboot the system.
> 
> .. is with the 9f2 every time !

You are giving me the error message, but where during the boot this message is shown?

**Comment by franklukas** [comment] 2019-12-14 17:08
Reading u:\c\mint\1-19-cur\mint.cnf ... 2281 bytes done.

VFAT active: AH

and than comes the error message

**Comment by franklukas** [comment] 2019-12-14 17:20
[https://fglukas.lima-city.de/forum/IMG_6845.jpg](url)

without the vfat line in the mint.cnf

**Comment by DavidGZ** [comment] 2019-12-14 17:23
OK, thanks!

**Comment by DavidGZ** [comment] 2019-12-16 09:53
Hi Frank, at first glance I don't think your current problem is related with the original one. Now it seems something related with lack of memory, according to the error message cwd is NULL and this happens when a malloc call fails, but I find very strange that you get out of memory so early even before XaAES is loaded. Also there is only 36 bytes of difference between the working kernel (1fd) and the one which doesn't (9f2). What do you have in your AUTO folder?

I've attached a new MiNT installation to confirm that is the malloc call that is failing. Tell me if some debug message comes out informing that a kmalloc failed.

[mint_cur.zip](https://github.com/freemint/freemint/files/3967201/mint_cur.zip)

**Comment by DavidGZ** [comment] 2019-12-16 10:34
I've tested MiNT on Hatari with 8 MiB of memory, similar capacity @franklukas has in his Falcon, the kernel fails to boot with kmalloc failing. So this is another problem from the original issue. I still find strange that 1fd kernel worked for you. Do you arrive to the desktop with that kernel?

We could close this issue and open a new one as a request to make a "light" kernel for 030 machines with few memory.

**Comment by franklukas** [comment] 2019-12-16 16:36
mint_cur.zip works for me ...

I can only run teradesk as desktop when I quit tos2win because 10MB of memory is not enough !

The Falcon has 4MB of ST Ram and 6MB of Fastram. All Fastram is used and there is no more available. STRam is 500kB free

**Comment by DavidGZ** [comment] 2019-12-16 17:03
> mint_cur.zip works for me ...
> 

Then I'm lost, the kernel in mint_cur.zip is kernel (9f2) with two debug messages added.

**Comment by DavidGZ** [comment] 2019-12-19 17:18
@franklukas I tried to simulate your Falcon with Hatari (4 MB ST-RAM and 6 MB TT-RAM), but kernel (9f2)  boots just fine on it, I needed to disable scc.xdd module because it make the system freeze during boot, I've read scc serial emulation is not mature enough on Hatari. 
I still find very strange that the installation attached 3 post above works but not 9f2. I'm thinking about the possibility that perhaps 9f2 got corrupted. Could you please install it again?

https://dl.bintray.com/freemint/freemint/snapshots/1-19-9f2ed80b/

**Comment by franklukas** [comment] 2019-12-19 18:08
The 9f2ed80b from the Link works fine ...

**Comment by DavidGZ** [comment] 2019-12-19 18:15
> The [9f2ed80](https://github.com/freemint/freemint/commit/9f2ed80bfebfe3d112a00d8588f579120fba37c1) from the Link works fine ...

Good! Thanks for the feedback.

**Closed** 2019-12-19 18:15 UTC
