### ISSUE TITLE
Bundled hyp_view.rsc is corrupted

### ISSUE THREAD

**Issue by czietz** [freemint/freemint#68] opened 2017-09-03 19:03 UTC
I noticed that the hyp_view.rsc that is bundled with the FreeMiNT snapshots (i.e. this file: https://github.com/freemint/freemint/blob/master/tools/hypview/hyp_view.rsc) is corrupted. Trying to start hyp_view.app gives the following error:

![img_2610](https://user-images.githubusercontent.com/9830685/30005815-1588c14a-90eb-11e7-8cf4-19db45d443e9.JPG)

I have confirmed with a hex editor that the file is indeed not a valid resource file. (The German version in the _de_ folder on the other hand works, BTW.)

**Comment by th-otto** [comment] 2017-09-04 00:01
Which program is displaying that alert in your screenshot? I think the resource is not really corrupted, but it is a RSM multilayer resource. ORCS eg. can load it without problems, but since it does not support that format completely, displays only the main layer.

**Comment by czietz** [comment] 2017-09-04 05:42
I guess the message comes from XaAES -- also bundled with the snapshot -- while loading the resource file. As I said, this happens when I'm just trying to launch hyp_view.app. 
Even if this was a valid RSC file, albeit in an unusual format, what good is it if the included AES cannot read it?

**Comment by mikrosk** [comment] 2017-09-04 05:57
Hmm, maybe it got corrupted by git transition. Does [the original](http://sparemint.org/cgi-bin/cvsweb/~checkout~freemint/tools/hypview/hyp_view.rsc?rev=1.4) work?

Also, "hyp_view" folder contains file `en.rsc`, not sure how different it is from the main `hyp_view.rsc` but it's worth trying as well.

**Comment by th-otto** [comment] 2017-09-04 15:02
@mikrosk the original is binary identical, so it did not get corrupted.

@czietz The problem is caused by 2 things:

- although the resource file contains color icons, it is not marked as such (bit 2 in the version field). That seems to be a bug in RSM.

- the version number in the header is 3, indicating an extended header with long offsets, as eg. written by interface. XaAES currently does not correctly support that format. As a result, the program crashes if you just ignore the message. Also, the standard resource size is much less than 64k, so this isn't actually needed. 

- solution: just copy one of {en,de,cz}.rsc as hyp_view.rsc to a folder where you start the app from (don't overwrite it in the main folder, as already said this is the multi-layer resource containing some informations for all 3 languages). Those single resource files seems to be ok.

output from my tool:
rschdr hyp_view.rsc
rsh_vrsn:     $0003
rsh_extvrsn:  $524d
rsh_object:   $0000007c
rsh_tedinfo:  $00000920
rsh_iconblk:  $00000ae8
rsh_bitblk:   $00000ce6
rsh_frstr:    $00000904
rsh_string:   $00000904
rsh_imdata:   $00001c18
rsh_frimg:    $00000920
rsh_trindex:  $00000060
rsh_nobs:     $0000005b (91)
rsh_ntree:    $00000007 (7)
rsh_nted:     $0000000e (14)
rsh_nib:      $0000000f (15)
rsh_nbb:      $00000000 (0)
rsh_nstring:  $00000007 (7)
rsh_nimages:  $00000000 (0)
rsh_rssize:   $00002886
filesize:     $00007b3e

rschdr ./hyp_view/en.rsc
rsh_vrsn:     $0004
rsh_object:   $0058
rsh_tedinfo:  $08fc
rsh_iconblk:  $0ac4
rsh_bitblk:   $0cc2
rsh_frstr:    $08e0
rsh_string:   $08e0
rsh_imdata:   $1460
rsh_frimg:    $08fc
rsh_trindex:  $003c
rsh_nobs:     $005b (91)
rsh_ntree:    $0007 (7)
rsh_nted:     $000e (14)
rsh_nib:      $000f (15)
rsh_nbb:      $0000 (0)
rsh_nstring:  $0007 (7)
rsh_nimages:  $0000 (0)
rsh_rssize:   $1e90
filesize:     $00007148

**Comment by czietz** [comment] 2017-09-04 16:12
Thank you, @th-otto, for the in-depth investigation! Since the snapshots come with XaAES, maybe the corresponding shell script could be updated to include the working hyp_view.rsc from the _en_ folder instead of the current one that is not compatible to XaAES.

**Closed** 2017-09-04 21:31 UTC

**Comment by mikrosk** [comment] 2017-09-04 21:32
Thanks guys, latest snapshot should be fine now (in a few minutes...).
