### ISSUE TITLE
some kernfs files contain NUL instead of EOL

### ISSUE THREAD

**Issue by paulwratt** [freemint/freemint#168] opened 2020-05-01 06:06 UTC
`cat /kern/2/environ`
the text is correct, but the EOL is not, confirmed with output of:
`cat /kern/2/environ | sort`
they are the same but they should (normally) be different

**Comment by vinriviere** [comment] 2020-05-01 07:28
`/kern/*/environ` variables are delimited with a NUL character. This is certainly by design.  So the contents can't be processed with standard filters.

To achieve what you want to do, you need to use:
`cat /kern/2/environ | xargs -0l1 | sort`

**Comment by th-otto** [comment] 2020-05-01 07:38
Vincent was faster ;)

Yes, this is by design. cat /proc/self/environ on linux does the same: the strings are delimited by NUL.

**Comment by mikrosk** [comment] 2020-05-01 07:40
I guess the same applies to `cmdline` and `fname`?

While we are at it, `/kern/sysdir` is without EOL by design, too?

**Comment by mikrosk** [comment] 2020-05-01 07:42
As far as `sysdir` is concerned, Vincent has discovered this 8 years ago: https://mikro.naprvyraz.sk/mint/201301/msg00179.html :-)

**Comment by paulwratt** [comment] 2020-05-01 09:43
ok thanks, I might change the topic to reflect this "feature". From AtariST standpoint it makes sense (smaller code and simpler use)

**Comment by vinriviere** [comment] 2020-05-01 10:51
> 
> 
> As far as `sysdir` is concerned, Vincent has discovered this 8 years ago: https://mikro.naprvyraz.sk/mint/201301/msg00179.html :-)

Indeed 😐 That `sysdir` not correctly terminated by EOL is clearly a misfeature.

**Comment by paulwratt** [comment] 2020-05-01 14:26
I found a the kernel filesystem page in the wiki and updated it, verifying which files are `NUL` terminated. I added commands that generate the quoted output, so the `cat | xargs -0l1` is obvious now (if one reads the wiki).
https://github.com/freemint/freemint/wiki/Kernel-Filesystem

its fine, `sysdir` gets used by code, and that would be complicated - ie the wiki page orginally said `^M` not `NUL`

**Comment by mikrosk** [comment] 2020-05-05 20:49
Nothing to be done here, closing.

**Closed by mikrosk** 2020-05-05 20:49 UTC
