### ISSUE TITLE
Duplicate symbols

### ISSUE THREAD

**Issue by th-otto** [freemint/freemint#181] opened 2020-05-21 17:15 UTC
While trying to compile freemint with GCC 10, i get duplicate symbols in some places. I have fixed already some of them, but there are still some remaining.

There are 2 things that cause this problem.
- until now, for global variables, gcc wrote something like
```#NO_APP
.comm _x,4
```
The new version now outputs
```        .globl  _x
        .bss
        .even
_x:
        .skip 4
```
I haven't found why yet, but the result is that you cannot longer declare uninitialized global symbols twice, and hope that the linker will merge them (as it does for the .comm directive)

- sys/usb/src.km/global.h includes tosdelay.c, where loopcount_1_msec and delay_1usec are declared. That now causes some targets to fail to link (looks like only the *.prg targets are effected)

@DavidGZ: could you have a look at that?

**Comment by vinriviere** [comment] 2020-05-21 17:34
> I haven't found why yet, but the result is that you cannot longer declare uninitialized global symbols twice, and hope that the linker will merge them (as it does for the .comm directive)

It's not a bug, its a feature. Didn't you read the release notes?
https://gcc.gnu.org/gcc-10/changes.html

_GCC now defaults to -fno-common. As a result, global variable accesses are more efficient on various targets. In C, global variables with multiple tentative definitions now result in linker errors. With -fcommon such definitions are silently merged during linking._

For information, EmuTOS has already been compiled with `-fno-common` for years.

**Comment by th-otto** [comment] 2020-05-21 17:44
> Didn't you read the release notes?

Oops. Must have missed that.

**Comment by DavidGZ** [comment] 2020-05-21 20:39
> @DavidGZ: could you have a look at that?

 Yes, I'll do it

**Comment by th-otto** [comment] 2020-05-22 06:52
Thanks. I came up with this patch, but maybe there is an easier solution.
[nocommon.patch.txt](https://github.com/freemint/freemint/files/4666516/nocommon.patch.txt)

**Comment by DavidGZ** [comment] 2020-05-22 07:09
OK, thanks for the patch, but after thinking about it I've taken a different approach, instead of including  tosdelay.c in global.h, we're going to compile it a link it as another regular c file, then we'll include tosdelay.h in the necessary files with the variables "extern" declarations.

**Comment by th-otto** [comment] 2020-05-22 07:17
I also though about that, but then i realized that there are also inline functions defined in it.

**Comment by DavidGZ** [comment] 2020-05-22 07:44
You're right, I didn't think about the inline functions not being inlined this way. Hmmm now I'm not sure what to do.
@Perdrix24 what do you think?

**Comment by DavidGZ** [comment] 2020-05-22 08:12
I'm going to discard my first idea, those inline functions in this code for timings should remain. Thanks hint @th-otto.

**Comment by DavidGZ** [comment] 2020-05-22 18:28
Fixed with this d8aecdb48171fc537efca82d0ab84065a84603fa and a91ee8e601e5f5dd981da4b0b4bb503e6f84278b.
But the tool fsetter fails to compile due to cflib.

I've just done a pull request in the cflib repo

**Closed** 2020-05-23 05:02 UTC
Labels: bug, build
