### ISSUE TITLE
MultiTOS AES does not work with current kernels

### ISSUE THREAD

**Issue by skaftetryne** [freemint/freemint#378] opened 2024-09-02 15:44 UTC
MultiTOS AES (the unofficial/unreleased 4.1 from Atari) does not work with current kernels. There's a problem with the keyboard, a key is stuck and there's no way to "unstick" it.

[GEM.SYS.zip](https://github.com/user-attachments/files/16839450/GEM.SYS.zip)

I've tried to both run it directly with GEM=... and launch it from a shell, and with and without NVDI.

**Comment by th-otto** [comment] 2024-09-02 16:10
I recently had the similar problem, but in my case keyboard was not working at all. I guess it is a similar problem as when using `GEM=ROM`: the timer handler for the keyboard will not fire, because the AES is running in supervisor mode all the time.

I also have problem with double-clicks there. Maybe due to similar issue.

**Comment by lpgb** [comment] 2024-09-02 16:29
Ran into this problem trying to do test aes tests. Works with an older 1.16 kernel that I happen to keep around.

**Comment by mikrosk** [comment] 2024-09-02 19:38
Duplicate of #173 ?

**Comment by vinriviere** [comment] 2024-09-03 09:19
> There's a problem with the keyboard, a key is stuck and there's no way to "unstick" it.

This is a very common problem when a program like FreeMiNT hooks the keyboard handler. At startup, the TOS waits for a key (i.e. TOS memory test, or EmuTOS welcome screen). The user presses a key, then the program (i.e. FreeMiNT) immediately hooks the keyboard **before the user has released the key**. So the TOS key repeat routine continues running behind the scenes, as the TOS keyboard handler never sees the key release event. This happens much more often on fast machines (and fast emulators), as the user has less time to release the key before the hook.

The unconvenient solution is to quickly tap the key at startup, so the key release event is received by the TOS before FreeMiNT hooks the keyboard. This can be tricky with very fast emulators such as ARAnyM.

I added a few hacks inside EmuTOS (and maybe FreeMiNT) to mitigate that issue. Obvious one being to wait for a key release before hooking the keyboard. Generally, with standard operation, this problem does not happen anymore with the couple EmuTOS+FreeMiNT. Of course, the problem still happens with plain TOS (unless I added some trick in FreeMiNT for TOS >= 2 extended keyboard handler, I don't remember well).

I don't know if this is really what happens with MultiTOS AES, but the symptoms are very similar.

**Comment by skaftetryne** [comment] 2024-09-03 11:41
It always happens, also when you don't touch the keyboard or mouse at all during powerup and booting. It reminds me of the problem that occured with N.AES sometime during 1.18 (IIRC) development.

**Comment by mikrosk** [comment] 2024-09-14 22:55
> It reminds me of the problem that occured with N.AES sometime during 1.18 (IIRC) development

And your hunch was correct, it is the same root cause as with #143, therefore it gets fixed by applying https://github.com/freemint/freemint/pull/379.

**Closed** 2024-10-07 06:57 UTC
