### ISSUE TITLE
Sub menu indicator off by one character

### ISSUE THREAD

**Issue by lpgb** [freemint/freemint#344] opened 2024-07-24 11:54 UTC
The sub menu indicator '>' triggered by menu_attach() is placed one character to far to the right. See attached image. The snapshot is from the exact same code running on xaaes (left) and naes (right). The indicator is covered up by the sub menu. It would be nice if it had a more consistent look with aes 4.1. I didn't include an image of Atari aes 4.1 as it looks identical to naes.

![side-by-side](https://github.com/user-attachments/assets/e62f1a9a-16f4-4b4f-b733-ba795c6fc305)

**Comment by th-otto** [comment] 2024-07-24 12:17
Hm, but then we have a problem. Typically, there is only 1 space to the right of the menu text, like in current versions of GBE:
![Screenshot_20240724_141330](https://github.com/user-attachments/assets/8bb2b453-7335-4b2f-821c-273d22e90851)

Also, you cannot assume that there are actually spaces to the right of the text, it may be that just the object width is set accordingly.

**Comment by lpgb** [comment] 2024-07-24 12:24
If you are going to attach a sub menu you have to adjust the string according which I did.

**Comment by GokMasE** [comment] 2024-07-24 21:01
**I actually stumbled into exactly this inconsistency about a year ago, when fine tuning the submenus in my taskbar project!**

(At the time I think I worked around it by manipulating the object width of the parental menu, but that resulted in wider than necessary sub menus IIRC)

### The glitch does seem like an occurance of the "off by one" error:

- The width of the submenu in XaAES seems equivalent to that of N.AES, the number of spaces at the end of the menu match perfectly in comparison. **OK!**

- Under XaAES the submenu is horizontally placed at the X-position corresponding to the very **last character position** of the entry that called for it - this seems to be the same that N.AES does from what I can tell. **OK!**

**..but now the problem kicks in:**
 
- The ">" char (which is indicating that a submenu is attached is present) is _ALSO_ placed x-wise on the **last character position** of the parental menu, rather than the NEXT TO LAST char position. **NOT OK!**
 
=> The result is that the newly opened submenu is located ON TOP of the ">" indicator, effectively clobbering it.

**End note: Lonny is also correct in that any menu entry that is planning to have a submenu attached, must ensure that the entry string is padded with spaces at the end - else the AES will indeed insert the ">" indicator inside the actual "text part" of the menu entry string!**

**Comment by th-otto** [comment] 2024-07-25 15:17
Pushed a fix for it. A small test program also attached below.

On another note: how does the accessory menu look like in N.AES or AES 4.1? I Always found it annoying to hover over the "Clients" entry first before you can see the accessories, but i have no idea how to handle that internally, since you cannot expect applications to have like 20 accessory menu entries.

[menuatt.zip](https://github.com/user-attachments/files/16379940/menuatt.zip)

**Comment by lpgb** [comment] 2024-07-25 16:33
The test program halts with "submenus not available" with naes and atari's aes 4.1.

**Comment by th-otto** [comment] 2024-07-25 16:44
Don't they have appl_getinfo()? If so just have to check for AES version, but i usually try to avoid that. Anyway, its just a quickly hacked together test, you can also use GBE to test it.

**Comment by lpgb** [comment] 2024-07-25 17:19
Yes appl_getinfo() is present. I think appl_find("?AGI") returns -1.

**Comment by GokMasE** [comment] 2024-07-25 19:33
**Thanks for the swift fix for this Thorsten, it seems to adjust the incorrect placement of the indicator as planned.**

**Now I just need to revert the changes I made in my app to workaround the original bug ;-)**

But I do have a remark here: I also notice that the indicator has been changed from the ">" char to the right arrow. While this indeed is making things look even closer to N.AES I'd say that this is more of an aesthatical detail than something that has a practical bearing.

I would have much prefered it if we kept the ">" char as indicator for submenus, as I feel that its presence has more to do with a style of choice than an oversight at the time of adding it. From my perspective I would also say that when having several submenus available in a menu view, the right arrow in plural then gives a much more busy and crowded look. The ">" gives a more clean and tidy impression especially in those situations I think.

Oftentimes it makes sense to have XaAES behave as close to N.AES as possible, but in such a visually minuor detail I think we could keep a little bit of "XaAES flavour" intact too.

**Comment by th-otto** [comment] 2024-07-26 03:21
As seen in the screenshots above, AES 4.1 als uses the arrow for submenus. And in the client menu, a down arrow is used, so imho its only consistent to use a right arrow for submenus. To me it also looks better. But i don't really mind. Its easy to change it back to `>` again.

**Comment by jflemaire** [comment] 2024-07-26 08:28
What happens if the user does not use the system font? Wouldn't the absence of these arrows in other fonts cause problems?

**Comment by th-otto** [comment] 2024-07-26 09:47
Maybe, yes. But the client menu would then also miss the down arrow.

**Comment by GokMasE** [comment] 2024-07-26 10:20
Yes, I realize also AES4.1 has the right arrow, N.AES usually mimics AES4.1 very closely. 

I get the idea to stay uniform (even if I think the long term goal is to get rid of the "clients" menu in one way or the other?) but also feel that since the ">" is more than likely a deliberate design choice of XaAES since (probably) the late 90s it also holds a valid legacy of its own.

For me personally, the difference is perhaps more striking than to others due to the application I am working on, the taskbar Motosu. This program is largely depending on submenus, it uses them a LOT. And having many of the indicators visible at a time really highlights the effect of using a different indicator, so atm this more "busy" look is a bit of a downer for me.

But if not changing back to ">", what about adding a config option for it? Something like this:

# submenu_indicator = <value>   (default = ?)
#
#  0 = right arrow (Same as AES4.1/N.AES)
#  1 = Greater than sign ">" (Classic XaAES)

Maybe this could potentially benefit users who wish to play with others fonts too, like @jflemaire mentioned?

**Comment by th-otto** [comment] 2024-07-27 03:17
Done now. This is a new app_option, so it can even be configured per application. Default is to use the right arrow.

**Comment by GokMasE** [comment] 2024-07-30 15:00
Thanks for adding it, I have installed the build and successfully configured the ">" sign back for the default target of app_options - that works nicely!

The fix I previously made in my own application to sort out the issue has also been reverted now, and from what I can see, the reported issue seems adequately sorted. I also notice that eg. aFTP no longer suffers from the clobbered submenu indicator (could be seen in GEM menu bar in XaAES prior to this bug being addressed)

All in all, it looks good so far and as of yet I see no new problems introduced by the patch. I will test a few more software titles tonight though.

Did anyone else test this patch yet?

**Comment by GokMasE** [comment] 2024-08-01 20:26
I think there is a regression here, see the indicator for the "Clients" menu? 


![indicator_bug](https://github.com/user-attachments/assets/cd973bec-7ced-4c0f-aea9-41d2c32c7b62)

**Comment by th-otto** [comment] 2024-08-02 04:34
Did you install also the new resource file (and maybe also the translations in *.rsl)?

**Comment by GokMasE** [comment] 2024-08-02 10:07
No, I didn't - and I can confirm installing the new xaaes.rsc resolves the issue.
The down arrow is now displayed correctly for the "Client" menu.

(When installing I did compare xaaes.rsc file sizes, and thought that identical file sizes indicated the files were the same - which was a bad assumption on my part)

If noone else can pick up any kind of regression or has objections to the patch, I would suggest this issue can be considered as resolved.

**Comment by th-otto** [comment] 2024-08-02 10:36
Yes, wrong assumption, there was only that single character changed from right to down arrow ;)

BTW i also looked how N.AES handles the accessory menu. Seems it changes the first accessory slot to "G_USERDEF", then uses that object to draw the accessory and client items.

**Closed by th-otto** 2024-08-02 10:36 UTC

**Comment by lpgb** [comment] 2024-08-10 22:43
@GokMasE suggested I try RSM in naes:
![naaes](https://github.com/user-attachments/assets/d92b25af-3f19-4c5e-a4ff-bdc9eb44cdca)

In xaaes I get this:
![xaaes](https://github.com/user-attachments/assets/51f08f85-0198-4cf8-b98f-01381383bc7a)

As I said above atari's aes and naes simply clobbers whatever character is already at that position. Moving the arrow to the end of the string causes the odd double arrow.

RSM already has an arrow in the drop down menu. Inspecting RSM's menu tree string:
![Screenshot 2024-08-10 at 5 33 55 PM](https://github.com/user-attachments/assets/ed2a4f2e-32e9-4ec2-b011-eaff015683c4)

Atm, this issues is not 100% fixed in my opinion.

Note: The submenu floating out in lala land is a different issue. Probably expect a new issue for that later. ;)

**Comment by th-otto** [comment] 2024-08-11 05:37
The double arrow is not a regression. Without the two patches regarding the positioning, or with the indicator changed back to '>', it looks like

![Screenshot_20240811_072117](https://github.com/user-attachments/assets/ea58b603-a6ea-4ab9-a64e-3347554ed276)

So it also displays both arrows. It just looks more strange when using an arrow ;)

Imho it is a bug in RSM to make the arrow part of the string, but should be fixed now with https://github.com/freemint/freemint/commit/3e509e566df2b40b112f9b414b71e7fe9101f951

**Comment by lpgb** [comment] 2024-08-11 07:01
I suspect the author of RSM put the arrows there as a reminder that a submenu will be attached. NAES and atari aes clobber whatever character you put there and he probably knew this.

**Comment by lpgb** [comment] 2024-08-11 14:25
Just tested this again. Now you have 2 new issues:
1) User doesn't want to see asc 3 (thick right arrows) as they set the config option you added to get greater than sign.
Now the menu doesn't match subsequent sub-menus in other parts of the program. RSM as an example.
2) In GBE I get double characters because it shifts the indicator to the end of the string which isn't what the other aes's do. Atari's aes and naes are perfectly fine with this and correctly replace the "$" with a thick right arrow. Note I can put any **random** character (>0) there and they don't care. 

![Screenshot 2024-08-11 at 9 06 55 AM](https://github.com/user-attachments/assets/40009b64-1298-49a2-86da-d7122cef9cb3)

I'll repeat this again for the 3rd or 4th time. Atari's aes and naes simply **clobber** whatever character is a that position. If you do that the end user will see the indicator they configured and it will properly mimic the other aes's.

**Comment by th-otto** [comment] 2024-08-12 07:51
> 1. RSM as an example.

RSM was already wrong without the fixes, as shown above.

I don't know why you think that AES is required to actually replace the character in the menu. I consider that as messing with the users data. Especially i don't understand why AES should react to such a '$' character. How should it know that you want it to be replaced, instead of displaying it? Why don't you just fill the entries with spaces, like is done for all other entries? The logic currently checks whether there is a space so that the arrow can be displayed there, otherwise it uses the last position of the string, for applications that "forget" to include enough room for the indicator there. Whether the arrow is written to the string, or just displayed, would not change that..

BTW, when you use menu_icheck, the AES does not modify the string to include that checkmark, either, it is just displayed.

**Comment by th-otto** [comment] 2024-08-12 10:41
Its not only about forgetting the padding. It is perfectly valid to define menu strings such that they don't contain trailing spaces, but have an object width that is larger than the strings length instead. IMHO it is a bug in AES 4.1/N.AES to violate that, and i don't think we should reproduce such bugs. Not to mention that it is not even specified anywhere that the objects have to be strings; this may be the case for menus, but not neccessarily for object trees constructed at runtime and used for form_popup().

But i'll think about it again how it can be handled better, so that atleast all current scenarios work as expected.

**Comment by th-otto** [comment] 2024-08-12 14:13
BTW, i still don't have access to your google drive with the beta versions (gbe 3.74 does not seem to use submenus). Can you make that available again?

**Comment by lpgb** [comment] 2024-08-13 12:45
That comment is uncalled for in the source, please remove it.
https://github.com/freemint/freemint/commit/07717e8dc70f3d573b4d45234d55de8a456c15e4#diff-3ed582f689576509a3d22dd566083f7ad9377a815bdcd8f0b33613acefb10df5R341
Atari's aes an naes are perfectly **fine** with it whether you think it's a bug or not. Who's to say a month from now, a year from now, someone else puts a different character there?

**Comment by shoggoth77** [comment] 2024-08-13 12:58
That’s just unacceptable. Why is that kind of thing even allowed into the source tree.

GBE is not a stupid application, it’s one of the bigger achievements on the platform and made by a very talented individual.

I think the respectful thing would be to retract the commit and reword that comment.

**Comment by th-otto** [comment] 2024-08-13 13:56
I didn't say that GBE is a stupid application, just that this expectation is just a bit stupid. There is no real reason to use a '$' there, a space would just suffice, making such workarounds unneccessary.

And there was no pun intended, XaAES (and also ORCS) all do a lot of stupid things.

What i really would like to here is, whether the current version now works as expected. I still can't test beta versions of GBE.

**Comment by mikrosk** [comment] 2024-08-13 14:13
Frankly, I have a hard time understanding all the drama. A quick look into TOS 4 release notes:

> To use pop-up menus and submenus in one's application:
> 
> [...]  If a menu item is 
> expected to have a submenu attachment, the G_STRING must be padded with blanks to the 
> width of the menu.  

Ok, cool, now Thorsten can celebrate because this is what he insists on. However later on:

> Attaching a submenu to a menu item is done by calling menu attach.  A submenu is associated 
> to a menu item by placing a right arrow two characters in from the right edge.  **Any characters 
> at that location will be overwritten**.

So while 'blanks' might imply spaces, now we have explicit confirmation that _any_ characters there will be overwritten. So that is what Lonny is saying.

So not only I don't see anything _stupid_ on the assumption that putting there `$` or whatever is fine, we have it confirmed even in the docs, if checking source code of AES4.1 isn't enough for some reason.

I'd say just revert the complex logic Thorsten, check for strlen >= 2 and overwrite whatever there is on [-2]. And remove that, erm, stupid, comment please.

**Comment by mikrosk** [comment] 2024-08-13 16:20
To me it looks like going in circles:

- three weeks ago Lonny tells you that he personally tested the behaviour in AES4.1 and N.AES and that all that is required is padding with whatever and all he is asking is to mimic this in XaAES, too
- that would fix the RSM case and not harass other applications (like GBE)
- somehow you interpreted it as RSM being a special case and handled its arrow explicitly
- this naturally made GBE not working properly and Lonny again reminded you that all that is needed is just overwrite the character
- you again came up with a more complex logic, instead of reverting the previous attempt
- then you argued that it's not clear whether the menu item must be string or whether it must be padded (which I later proved by the TOS4 release notes)
- and now you argue that hypothetically we could need replacing the indicator with something non-textual while there are still scenarios when the current code can break but  you are tired of fixing it again

I mean... why? Why all of this? You are certainly experienced enough to know that you, as the developer, have always two options:
- provide a minimalistic fix for given problem, ideally by testing what other implementations do
- provide a more robust fix with some extra features (like our `>` vs `->` feature) but then you have to be prepared for maintenance / after-release bugfixing because such changes rarely work on the first attempt

It really reminds me some of Helmut's darker days where he did exactly that - fixed one thing, broke 10 others and told everyone "keep it or remove it, I don't care, not interested anymore". I guess we all agree that this is not the desired approach anymore.

**Comment by th-otto** [comment] 2024-08-13 17:27
> Why all of this?

To summarize:

- before the fixes, the indicator was placed at the last character of the string. Until recently (apparently because there are not that many applications that make use of menu_attach()) this was not noticed. Not even for RSM, because the length of the strings is one shorter than the menu width, so the popup menu did not clobber the indicator. It still looked strange, because 2 indicators were displayed, but no one complained so far.
- Using the toolbar demo, and with beta versions of GBE. it was obvious that with the original code, the popup would clobber the indicator. So that had to be fixed. However replacing the character inplace seemed not an option to me, because menu_attach() is also used for the vertically attached client menu in the desktop. That not only uses a vertical arrow, but also has that arrow character in the last position of the string.
- that worked well, until lp came up with a new beta version of GBE (still not available for testing), which now uses "$" instead of a space, for whatever reason. That forced me to change the code again. I was a bit upset by this, because imho it is completely unnecessary.

> ideally by testing what other implementations do

To say "we have to do it that way because N.AES does it too" is not really a good argument. For the same reason you could open an issue for everything were XaAES behaves differently, including how windows/objects are rendered. If you want it to be totally equal, then just use N.AES, and we can completely get rid of XaAES altogether, because every change we make would be incompatible in one way or the other.

**Comment by GokMasE** [comment] 2024-08-13 17:45
My final comment on this topic: I always thought it made sense to stay close to the original AES (and thus N.AES, since they behave so similar), to make sure applications behave in a predictable way (which to me has always been a high priority) - at least when there is no **obvious gain** by taking a different approach. Like new features, or prevent serious issues like a crash or similar. When it comes to my own issue reporting made so far, it is pretty much based on that thinking. XaAES has been taking a lot of small such steps to behave more "predictable" in that sense and as a result, now has way better conformity with the others AES's. That is my take on how to refine XaAES, and until now I honestly thought it was a rather safe thing to assume was also desirable for everybody. To say "if you want things to behave like N.AES, just use N.AES" is pretty much the same as suggesting that this kind of reports are now considered not welcome....

Considering the utter deadlock in the current discussion, I conclude that it is time for me to agree to disagree and move on from this topic.

I will focus my energy on issues where there are chances to reach an understanding.

**Comment by th-otto** [comment] 2024-08-15 08:12
>XaAES explicitly works around applications which forget to call appl_init(), don't do this or that which worked in TOS by chance.

That applies to old programs that can't be changed. But i don't see the point of implementing ugly workarounds for programs that are actively developed. IMHO the programs should be fixed, not XaAES.

> So please, don't over-engineer things there. Just fix it with the strlen >= 2 && [-2]. The option for replacing the arrow with

How often do i have to repeat this? This does not work, because attach_menu is also used to attach the vertical client menu.

**Comment by mikrosk** [comment] 2024-08-15 08:19
> That applies to old programs that can't be changed. But i don't see the point of implementing ugly workarounds for programs that are actively developed. IMHO the programs should be fixed, not XaAES.

Sorry what old programs? I really like the three-arrow submenu indicator in my current, 2024 program and I expect XaAES to show it the same way as AES4.1, N.AES and MyAES. Currently this isn't the case.

> How often do i have to repeat this? This does not work, because attach_menu is also used to attach the vertical client menu.

If you mean in XaAES source code, adding a flag whether it's horizontal or vertical menu doesn't seem very hard.

**Comment by lpgb** [comment] 2024-08-16 07:55
I downloaded the source and built xaaes locally as I find the current solution poor at best. Shifting the indicator to right more or less results in an off by 1 error like I originally reported. Then the submenu again covers the indicator. 

I kindly submit this patch. It works with all my weird test cases and the down arrow in the client menu is intact. It follows Atari's rules a little better which results in a more consistent look across all 3 aes's.

Tested RSM, aes demo, gbe, and all seem fine.

Tweak for menuwidg.c
```C
			if (mn != &desk_popup && (attach_to->ob_type & 0xff) == G_STRING)
			{
				char *text;
				int len;
				/*
				 * Atari's AES doesn't enforce the padding whatsoever.
				 * The indicator must be placed at strlen()-2 per Atari.
				 * Atari's AES simply clobbers whatever character is there and
				 * doesn't care what is on either side of it and displays it as is.
				 * Put a space there so it doesn't appear on top of another character.
				 */
				text = object_get_spec(attach_to)->free_string;
				len = (int)strlen(text);
				if (len >= 2 )
					text[len - 2] = ' ';
			}
```

Tweak for render_obj.c
```C
			if (ob->ob_flags & OF_SUBMENU)
			{
				int len = strlen(t);
				if (len > 0 && t[len - 1] != '\002')
				{
					char indicator[2];
					/*
					 * The indicator must be placed at strlen()-2 per Atari.
					 * Function attach_menu() should have clobbered it with a space.
					 * Double check the space so it don't render on top of something.
					 */
					if (len >= 2 && t[len - 2] == ' ')
						r.g_x += (len - 2) * screen->c_max_w;

					indicator[0] = wt->owner->options.submenu_indicator == 0 ? '\003' : '>';
					indicator[1] = '\0';
					ob_text(wt, v, NULL, ct, &r, &wt->r, NULL, -1, -1, -1, -1, 0,0,0, indicator, state, flags, -1, G_BLACK);
				}
			}
```
