### ISSUE TITLE
Latest snapshot e43480ab does not include ST/68000 binaries

### ISSUE THREAD

**Issue by czietz** [freemint/freemint#122] opened 2019-06-14 06:09 UTC
I just wanted to point someone to the latest (as of now) FreeMiNT snapshot to try on his ST, but the ST/STE binaries are missing from: https://bintray.com/freemint/freemint/snapshots/1-19-e43480ab

**Comment by mikrosk** [comment] 2019-06-14 06:23
Yes, downloading libcmini was halted (github lag or something), I restarted the build and should be fine now.

Thanks for spotting that (I guess in this case only the person who had committed the last change got notified).

**Closed by mikrosk** 2019-06-14 06:23 UTC

**Comment by DavidGZ** [comment] 2019-06-14 08:24
>Thanks for spotting that (I guess in this case only the person who had committed the last change got notified).

That was me :-) The problem is that I get notified every time I push something so I'm not looking into it anymore because if I understood correct there is known issue.

**Comment by mikrosk** [comment] 2019-06-14 08:29
@DavidGZ it is always good to look why travis build fails - if it is something like a github/travis/bintray issue, just restart given sub-build and let it be, if it is something else, it's good to check it (a typo, linker error etc).

Restarting build is harmless, esp. for archives which didn't get uploaded at all.

**Comment by mikrosk** [comment] 2019-06-14 08:44
>  The problem is that I get notified every time I push something so I'm not looking into it anymore because if I understood correct there is known issue.

Actually this is not true anymore - I bit the bullet and authorised myself for github downloads in freemint project: https://github.com/freemint/travis-scripts/blob/freemint-master/install.sh ... so we shouldn't really experience any hard public limits for some quite time already. So if you see a build failing because of some libcmini, it is a serious bug, not expected behaviour.

**Comment by mfro0** [comment] 2019-06-15 18:53
Would it help if I'd provide a github access token to the libcmini
repository?


Am Donnerstag, den 13.06.2019, 23:23 -0700 schrieb Miro Kropáček:

**Comment by mikrosk** [comment] 2019-06-15 21:12
> Would it help if I'd provide a github access token to the libcmini repository?

It doesn't matter whose token it is - the important thing is to use one (what we do for some time now). So on the libcmini side everything as good as it gets.
