### ISSUE TITLE
XaAES doesn't reuse window handle IDs 

### ISSUE THREAD

**Issue by GokMasE** [freemint/freemint#239] opened 2022-01-29 23:12 UTC
When requesting a new window handle through WIND_CREATE(attr,..) XaAES will supply window handle IDs that steadily increases regardless if any of the previously supplied handles has been released through WIND_DELETE() - this means XaAES isn't at all reusing window handle IDs that are no longer in use.

Given the comment by HR (Henk Robbers?) in c:_window.c I would guess that the current behaviour is not the desired one:

https://github.com/freemint/freemint/blob/master/xaaes/src.km/c_window.c#L54

/* HR:
 * I hated the kind of runaway behaviour (return wind_handle++)
 * So here is my solution:
 * Window handle bit array (used to generate unique window handles)
 * As this fills up, there may be a problem if a user opens
 * more than MAX_WINDOWS windows concurrently :-)
 */
 
 
 
Furthermore - and more troublesome: 
 
The max number of windows allowed seems to be set at 4096, and the current code that supplies window handles appears to be based on that. Interestingly, XaAES will happily hand out window handles beyond that, up to 4128, at which point things go obviously bonkers.

Any call to WIND_CREATE() after handle ID has reached 4128 first time will all render in ID=4128 as window handle ID. It would be logical to either receive an error or having XaAES starting to reuse previously released handle IDs. As a test I first opened a desktop window in Thing (which then is given the handle ID 4128), and then hit CTRL+N in HighWire to open a new browser window (which then also is given the same handle ID, 4128). Interestingly, HighWire then adopted the already present Thing window, overwriting the contents! Admittedly, you will have to work hard to push the ID of the window handles to figures up towards 4128 but the current implementation of window handle ID creation seems rather troubled.

(Side note: I am not sure it matters, but to me it looked odd that the window handles aren't increased by +1 for each WIND_CREATE/WIND_DELETE cycle, but rather with +3)

**Comment by mikrosk** [comment] 2022-02-05 10:29
Out of curiosity, what is your use case here? I mean, opening and closing 4000+ windows seems like quite a work. ;-)

**Comment by GokMasE** [comment] 2022-02-05 10:50
It is very excessive work of course, and it will take quite some time before it poses a problem for any normal session. The only reason for writing such a test program was in order to diagnose the full nature of the bug.

The real problem is that old window handles that are no longer in use are obviously not freed and made available - hence the window handle ID is ever increasing. 

The 2nd problem is a more theoretical one - at the point where XaAES runs out of window handles, it should report back an error to any app calling WIND_CREATE() I think.

**Comment by th-otto** [comment] 2022-02-05 11:23
On Samstag, 5. Februar 2022 11:51:08 CET Joakim wrote:
>  hence the window handle ID is ever increasing.

You can also see that as feature. Imagine something like:

win = wind_find(x, y)

and the returned window belongs to another application. However, before that 
function returns, and you get the handle back, the application terminates, 
another application starts, and gets the same window id becuse it is free 
now...

**Comment by shoggoth77** [comment] 2022-02-05 14:08
My impression is that two clients end up getting the same ID when the system is stressed. That's not a feature, it's a bug.

**Comment by shoggoth77** [comment] 2022-02-05 14:12
4000 windows is of course a synthetic case, men one can easily get the impression that the large pool of handles were chosen to hide the problem rather than fixing it. There is obviously no need to have 4000 windows open :-)

**Comment by lpgb** [comment] 2022-02-05 14:15
It never frees a window handle under any circumstances and this breaks one of my apps. GokMasE left a machine running for several days and the window handles returned were up ever 640.

**Comment by GokMasE** [comment] 2022-02-05 15:07
In my mind it is easy as this:

1) The handle IDs are constantly increased, for each time a process requests a new one  (side note: Is memory for old and now unused handles in fact simply going to waste?)
2) The supply of handle IDs is not infinite 
3) Bad things happen when the finite supply runs out and someone requests another one..

If it walks like a bug, and looks like a bug, it is probably a bug.

The intial large pool of handle IDs just manages to hide the problem for shorter sessions, but in the long run (when enough calls have been made to WIND_CREATE), this will eventually lead to problems. For a system component like an AES (that I expect to be efficient and accurate) I would not personally consider the current behaviour acceptable.

**Comment by skaftetryne** [comment] 2022-02-05 22:39
On Sat, 2022-02-05 at 06:12 -0800, shoggoth77 wrote:
> 4000 windows is of course a synthetic case, men one can easily get
> the impression that the large pool of handles were chosen to hide the
> problem rather than fixing it. There is obviously no need to have
> 4000 windows open :-)

Doesn't XaAES use windows for it's menus? If so, does it use normal
windows (and consumes window id's) or some custom/reserved windows? If
it consumes window id's then the window id usage per application
increases a lot.

Instead of simply ++ the previous window handle when creating a new
window, it should look for the *next* free window handle. When reaching
the max handle number, wrap around and start from 0 again.

Btw I'm running a really old kernel/XaAES from 2014 on my Milan, simply
because the more recent ones does not work for me (crashes at
apparently random places during boot). Been programming on and off for
12 hours without a reboot, constantly testing a GEM-app that creates
three windows every time. Window handle is currently at 28 here.

Jo Even

**Comment by GokMasE** [comment] 2022-02-27 12:06
**I can now conclude that this bug does NOT exist on XaAES-Ozk - (See https://github.com/freemint/freemint/issues/241)**

It is however worth mentioning that the actual release of Handle IDs has some sort of time based condition built-in, seemingly by design.  

XaAES-Ozk will in fact reuse window handles perfectly, as long as there is a delay of >5ms between the last WIND_DELETE() and the next WIND_CREATE(). The scheme appears to work similar to a garbage collection which is only carried out under certain circumstances (or possible at a regular interval). My conclusion is  that, yes, you *can* purpously provoce XaAES-Ozk to reach the end of the "slot buffer" (which then seems to be at 4098 rather than 4128 for "XaAES-current") and start getting bogus handle IDs back - but that is nowhere near possible within anything that resembles a normal or even foreseeable situation in GEM. 

**But if we then look at "XaAES-current", I have yet to find a situation where Handle IDs are actually freed and made available for reuse - if there is a mechanism that is supposed to carry out some kind of regular maintainance (similar to clean up/garbage collection/etc) then I suspect that either that is broken, and/or something limited to the actual Handle ID-management.**

**Comment by skaftetryne** [comment] 2022-02-27 16:01
Just tested this on my "daily driver" MiN/T/XaAES installation which is from 2014, and window handles are re-used.

- Created a window which was assigned handle 14.
- Exited the application and started it again. The new window was also assigned handle 14.
- Started the application, the started another application and opened a few windows. Started the test-application again and confirmed that the two instances was assigned different handles. Exited all applications and started the test-application again. Window handle 14 again.

**Comment by GokMasE** [comment] 2022-02-27 20:17
> Just tested this on my "daily driver" MiN/T/XaAES installation which is from 2014, and window handles are re-used.

Ok, it is good information to anyone interested in digging through the sources that the bug was introduced somewhere between 2014-2022.

**Comment by mikrosk** [comment] 2022-04-16 09:48
Actually the conclusions drew in this thread are not correct. There isn't a "windows_handle_counter++" style of code, it's done properly, as described by Henk -- using a bitfield and this bitfield always release destroyed handles, making them available for next wind_create().

What is the issue though is this change by @th-otto: https://github.com/freemint/freemint/commit/7c9ba347#diff-310a2657d3ce87ecd2261e4f8acd3583bf54c7181c65df34d8252c39a3a7ac35R2715 which disabled calling to `delete_window1` and thefore releasing the handles... to me it looks like an obvious typo but I'll let Thorsten to comment, just to be sure.

**Comment by th-otto** [comment] 2022-04-16 10:26
Yes, looks like a typo (or better to say a misplaced #endif)

**Closed** 2022-04-16 11:19 UTC
Labels: xaaes
