### ISSUE TITLE
Problem with AtariForge SMTP / mailing lists?

### ISSUE THREAD

**Issue by vinriviere** [freemint/freemint#57] opened 2017-06-17 08:13 UTC
I have a message pending in Google's mail server:

> Final-Recipient: rfc822; freemint-list@mail.atariforge.org
> Action: delayed
> Status: 4.4.1
> Diagnostic-Code: smtp; The recipient server did not accept our requests to connect. Learn more at https://support.google.com/mail/answer/7720 
>  [mail.atariforge.org 96.32.243.245: generic::failed_precondition: connect error (0): error]

Also, when trying to connect directly to AtariForge SMTP:
> $ telnet mail.atariforge.org 25
> Trying 96.32.243.245...
> (infinite wait)

I'm not sure if the command above usually works, though.

Anyway: is there something wrong with AtariForge SMTP?

**Comment by mikrosk** [comment] 2017-06-17 08:23
Same here, can't send emails. Also the web archive is down. @rmahlert @atic-atac do you know something?

**Comment by th-otto** [comment] 2017-06-17 08:26
> Anyway: is there something wrong with AtariForge SMTP?

telnet mail.atariforge.org 25
Trying 96.32.243.245...
telnet: connect to address 96.32.243.245: No route to host

Seems more a problem with some DNS server?

**Comment by rmahlert** [comment] 2017-06-17 16:05
Rebooted server..

**Comment by mikrosk** [comment] 2017-06-17 22:53
Getting emails again, so "fixed".

**Comment by zabruder** [comment] 2017-09-16 15:20
Even though the issue is closed, I want to add that I don't receive any mails from the list since Feb. May be it's related to my ISP, but other mailing-lists do work.

**Comment by mikrosk** [comment] 2017-09-16 22:28
@zabruder what happens if you send an email to the list?

Also, there is something odd about your email: I have a special rule in gmail just not to add your emails to spam -- without it 99% of your emails ended up there.

**Comment by mikrosk** [comment] 2017-10-14 03:34
@rmahlert @atic-atac

Can't access http://mail.atariforge.org/mailman/listinfo/freemint-list at all. It says:

> This site can’t be reached
> 
> http://mail.atariforge.org/mailman/listinfo/freemint-list is unreachable.
> ERR_ADDRESS_UNREACHABLE
> 

Emails are hopefully still getting trough.

**Comment by rmahlert** [comment] 2017-10-15 00:47
Back up

**Comment by mikrosk** [comment] 2017-10-15 01:20
Seems to be working now, closing. Thanks!

**Comment by mikrosk** [comment] 2017-10-31 05:34
... and the server is down again. Guys, this is getting unbearable. The number of developers is less than 10 and even those can't communicate to each other (@zabruder can't access the list at all for instance).

@anodynesoftware and @atic-atac are listed as admins for https://sourceforge.net/projects/freemint, what about setting the mailing list there, same as [EmuTOS does](https://sourceforge.net/projects/emutos/lists/emutos-devel). Another alternative is to use Google Groups, same as [Aranym does](https://groups.google.com/forum/?hl=en#!forum/aranym).

I'm happy to setup either of the options for you (I would need an admin access to the SF.net page then), I just need some final word.

**Comment by th-otto** [comment] 2017-10-31 05:51
I think the goal is to move away from SF, dunno wether it makes sense to set up a ML there. But i'm not fond of google-groups either. But since i also have no better idea *shrug*

**Comment by atic-atac** [comment] 2017-10-31 08:01
@mikrosk what is your handle on SF ?

**Comment by mikrosk** [comment] 2017-10-31 08:03
@atic-atac: mikro_sk

**Comment by atic-atac** [comment] 2017-10-31 08:03
@mikrosk done. you are now an admin on SF.

**Comment by mikrosk** [comment] 2017-10-31 08:07
Great. So what's your opinion, Alan? I think sf.net mailing list infrastructure will be with us for some time, it's much more used than google groups for OSS projects and as a bonus, it provides a file storage (something which EmuTOS uses to its benefit for snapshots).

Although there are other solutions, @th-otto implemented a bintray account for Aranym, so it's not the only way. @mfro0, @vinriviere, @zabruder: opinions, preferences?

**Comment by atic-atac** [comment] 2017-10-31 08:09
I'm happy with mailing lists on SF.

**Comment by mfro0** [comment] 2017-10-31 08:22
I don't care where the mails come from as long as they keep coming ;)

AtariForge reliablity is a concern indeed. I'm actually thinking about moving my projects from there to GitHub as well.

**Comment by atic-atac** [comment] 2017-10-31 08:43
Hat's off to Rob for trying, but he really doesn't have time to manage AtariForge, and it's not upd-to-date at all. So I won't be using AtariForge anymore.

**Comment by th-otto** [comment] 2017-10-31 08:48
He should just get it up running again once, so he can see all the mails that want to thank him for keeping it up for so long ;)

**Comment by mikrosk** [comment] 2017-10-31 09:40
OK, I have setup https://sourceforge.net/p/freemint with some graphics and information. They even offer github integration, i.e. when we release something on github, they add it to their file section (so it's not so sad and empty). There was also a possibility to redirect https://freemint.sourceforge.io to https://freemint.github.io which I gladly used. ;)

So... should I send an email to everyone that they should subscribe to https://sourceforge.net/p/freemint/mailman ?

P.S. https://lists.sourceforge.net/lists/admin/freemint-discuss is still owned by @atic-atac and @anodynesoftware i.e. I couldn't change anything in there. I hope you guys remember the admin password. ;)

**Comment by mikrosk** [comment] 2017-10-31 11:04
Done. Changed in the wiki, FreeMiNT project website, advertised in comp.sys.atari.st, aranym, emutos, hatari, atari-forum.com, debian/m68k, netbsd/m68k, the old freemint-list + all subscribed individuals (plus a few others which perhaps never made it to the list like Helmut or Johan).

@rmahlert thanks for all the service, it was worth a try.

**Closed** 2017-10-31 11:05 UTC

**Comment by rmahlert** [comment] 2017-10-31 12:37
Storm knocked out power for a day and internet is still down. Even cell
service is spotty.

Rob

**Comment by vinriviere** [comment] 2017-11-02 09:25
Based on my experience on EmuTOS: SourceForge mailing lists are not ideal.

Cons:
- A footer with an advert is added at the end of each message, that's ugly.
- Some users never received some messages because their mailserver's antispam considered that advert link as spam. This only happened 1 or 2 times, not a general issue.
- A few months ago, when SourceForge has changed its policies, some users have been silently unregistered from the mailing list (including me). This was a one-time problem, should not happen again
- It is no more possible to see the list of subscribers, even for administrators

Pros:
- Does the job, anyway.
- Subscription is possible without a SourceForge account.
- A lot of mailing list options, including antispam, content filtering, etc.
- Message delivery time is acceptable (about 30 seconds)

On the other hand, I have no experience on other mailing lists systems. Google Groups used by ARAnyM looks nice, but I have not used it much. Tuxfamily used by Hatari has very fast delivery times.
